// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Qot_UpdateOrderDetail.proto

package Qot_UpdateOrderDetail;

public final class QotUpdateOrderDetail {
  private QotUpdateOrderDetail() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface S2COrBuilder extends
      // @@protoc_insertion_point(interface_extends:Qot_UpdateOrderDetail.S2C)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *股票
     * </pre>
     *
     * <code>required .Qot_Common.Security security = 1;</code>
     */
    boolean hasSecurity();
    /**
     * <pre>
     *股票
     * </pre>
     *
     * <code>required .Qot_Common.Security security = 1;</code>
     */
    Qot_Common.QotCommon.Security getSecurity();
    /**
     * <pre>
     *股票
     * </pre>
     *
     * <code>required .Qot_Common.Security security = 1;</code>
     */
    Qot_Common.QotCommon.SecurityOrBuilder getSecurityOrBuilder();

    /**
     * <pre>
     *卖盘
     * </pre>
     *
     * <code>required .Qot_Common.OrderDetail orderDetailAsk = 2;</code>
     */
    boolean hasOrderDetailAsk();
    /**
     * <pre>
     *卖盘
     * </pre>
     *
     * <code>required .Qot_Common.OrderDetail orderDetailAsk = 2;</code>
     */
    Qot_Common.QotCommon.OrderDetail getOrderDetailAsk();
    /**
     * <pre>
     *卖盘
     * </pre>
     *
     * <code>required .Qot_Common.OrderDetail orderDetailAsk = 2;</code>
     */
    Qot_Common.QotCommon.OrderDetailOrBuilder getOrderDetailAskOrBuilder();

    /**
     * <pre>
     *买盘
     * </pre>
     *
     * <code>required .Qot_Common.OrderDetail orderDetailBid = 3;</code>
     */
    boolean hasOrderDetailBid();
    /**
     * <pre>
     *买盘
     * </pre>
     *
     * <code>required .Qot_Common.OrderDetail orderDetailBid = 3;</code>
     */
    Qot_Common.QotCommon.OrderDetail getOrderDetailBid();
    /**
     * <pre>
     *买盘
     * </pre>
     *
     * <code>required .Qot_Common.OrderDetail orderDetailBid = 3;</code>
     */
    Qot_Common.QotCommon.OrderDetailOrBuilder getOrderDetailBidOrBuilder();
  }
  /**
   * Protobuf type {@code Qot_UpdateOrderDetail.S2C}
   */
  public  static final class S2C extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Qot_UpdateOrderDetail.S2C)
      S2COrBuilder {
  private static final long serialVersionUID = 0L;
    // Use S2C.newBuilder() to construct.
    private S2C(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private S2C() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private S2C(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              Qot_Common.QotCommon.Security.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) != 0)) {
                subBuilder = security_.toBuilder();
              }
              security_ = input.readMessage(Qot_Common.QotCommon.Security.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(security_);
                security_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
            case 18: {
              Qot_Common.QotCommon.OrderDetail.Builder subBuilder = null;
              if (((bitField0_ & 0x00000002) != 0)) {
                subBuilder = orderDetailAsk_.toBuilder();
              }
              orderDetailAsk_ = input.readMessage(Qot_Common.QotCommon.OrderDetail.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(orderDetailAsk_);
                orderDetailAsk_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000002;
              break;
            }
            case 26: {
              Qot_Common.QotCommon.OrderDetail.Builder subBuilder = null;
              if (((bitField0_ & 0x00000004) != 0)) {
                subBuilder = orderDetailBid_.toBuilder();
              }
              orderDetailBid_ = input.readMessage(Qot_Common.QotCommon.OrderDetail.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(orderDetailBid_);
                orderDetailBid_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000004;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Qot_UpdateOrderDetail.QotUpdateOrderDetail.internal_static_Qot_UpdateOrderDetail_S2C_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Qot_UpdateOrderDetail.QotUpdateOrderDetail.internal_static_Qot_UpdateOrderDetail_S2C_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Qot_UpdateOrderDetail.QotUpdateOrderDetail.S2C.class, Qot_UpdateOrderDetail.QotUpdateOrderDetail.S2C.Builder.class);
    }

    private int bitField0_;
    public static final int SECURITY_FIELD_NUMBER = 1;
    private Qot_Common.QotCommon.Security security_;
    /**
     * <pre>
     *股票
     * </pre>
     *
     * <code>required .Qot_Common.Security security = 1;</code>
     */
    public boolean hasSecurity() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     *股票
     * </pre>
     *
     * <code>required .Qot_Common.Security security = 1;</code>
     */
    public Qot_Common.QotCommon.Security getSecurity() {
      return security_ == null ? Qot_Common.QotCommon.Security.getDefaultInstance() : security_;
    }
    /**
     * <pre>
     *股票
     * </pre>
     *
     * <code>required .Qot_Common.Security security = 1;</code>
     */
    public Qot_Common.QotCommon.SecurityOrBuilder getSecurityOrBuilder() {
      return security_ == null ? Qot_Common.QotCommon.Security.getDefaultInstance() : security_;
    }

    public static final int ORDERDETAILASK_FIELD_NUMBER = 2;
    private Qot_Common.QotCommon.OrderDetail orderDetailAsk_;
    /**
     * <pre>
     *卖盘
     * </pre>
     *
     * <code>required .Qot_Common.OrderDetail orderDetailAsk = 2;</code>
     */
    public boolean hasOrderDetailAsk() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <pre>
     *卖盘
     * </pre>
     *
     * <code>required .Qot_Common.OrderDetail orderDetailAsk = 2;</code>
     */
    public Qot_Common.QotCommon.OrderDetail getOrderDetailAsk() {
      return orderDetailAsk_ == null ? Qot_Common.QotCommon.OrderDetail.getDefaultInstance() : orderDetailAsk_;
    }
    /**
     * <pre>
     *卖盘
     * </pre>
     *
     * <code>required .Qot_Common.OrderDetail orderDetailAsk = 2;</code>
     */
    public Qot_Common.QotCommon.OrderDetailOrBuilder getOrderDetailAskOrBuilder() {
      return orderDetailAsk_ == null ? Qot_Common.QotCommon.OrderDetail.getDefaultInstance() : orderDetailAsk_;
    }

    public static final int ORDERDETAILBID_FIELD_NUMBER = 3;
    private Qot_Common.QotCommon.OrderDetail orderDetailBid_;
    /**
     * <pre>
     *买盘
     * </pre>
     *
     * <code>required .Qot_Common.OrderDetail orderDetailBid = 3;</code>
     */
    public boolean hasOrderDetailBid() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <pre>
     *买盘
     * </pre>
     *
     * <code>required .Qot_Common.OrderDetail orderDetailBid = 3;</code>
     */
    public Qot_Common.QotCommon.OrderDetail getOrderDetailBid() {
      return orderDetailBid_ == null ? Qot_Common.QotCommon.OrderDetail.getDefaultInstance() : orderDetailBid_;
    }
    /**
     * <pre>
     *买盘
     * </pre>
     *
     * <code>required .Qot_Common.OrderDetail orderDetailBid = 3;</code>
     */
    public Qot_Common.QotCommon.OrderDetailOrBuilder getOrderDetailBidOrBuilder() {
      return orderDetailBid_ == null ? Qot_Common.QotCommon.OrderDetail.getDefaultInstance() : orderDetailBid_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasSecurity()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasOrderDetailAsk()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasOrderDetailBid()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getSecurity().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getOrderDetailAsk().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getOrderDetailBid().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeMessage(1, getSecurity());
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeMessage(2, getOrderDetailAsk());
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        output.writeMessage(3, getOrderDetailBid());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getSecurity());
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getOrderDetailAsk());
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getOrderDetailBid());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Qot_UpdateOrderDetail.QotUpdateOrderDetail.S2C)) {
        return super.equals(obj);
      }
      Qot_UpdateOrderDetail.QotUpdateOrderDetail.S2C other = (Qot_UpdateOrderDetail.QotUpdateOrderDetail.S2C) obj;

      if (hasSecurity() != other.hasSecurity()) return false;
      if (hasSecurity()) {
        if (!getSecurity()
            .equals(other.getSecurity())) return false;
      }
      if (hasOrderDetailAsk() != other.hasOrderDetailAsk()) return false;
      if (hasOrderDetailAsk()) {
        if (!getOrderDetailAsk()
            .equals(other.getOrderDetailAsk())) return false;
      }
      if (hasOrderDetailBid() != other.hasOrderDetailBid()) return false;
      if (hasOrderDetailBid()) {
        if (!getOrderDetailBid()
            .equals(other.getOrderDetailBid())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasSecurity()) {
        hash = (37 * hash) + SECURITY_FIELD_NUMBER;
        hash = (53 * hash) + getSecurity().hashCode();
      }
      if (hasOrderDetailAsk()) {
        hash = (37 * hash) + ORDERDETAILASK_FIELD_NUMBER;
        hash = (53 * hash) + getOrderDetailAsk().hashCode();
      }
      if (hasOrderDetailBid()) {
        hash = (37 * hash) + ORDERDETAILBID_FIELD_NUMBER;
        hash = (53 * hash) + getOrderDetailBid().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Qot_UpdateOrderDetail.QotUpdateOrderDetail.S2C parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Qot_UpdateOrderDetail.QotUpdateOrderDetail.S2C parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Qot_UpdateOrderDetail.QotUpdateOrderDetail.S2C parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Qot_UpdateOrderDetail.QotUpdateOrderDetail.S2C parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Qot_UpdateOrderDetail.QotUpdateOrderDetail.S2C parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Qot_UpdateOrderDetail.QotUpdateOrderDetail.S2C parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Qot_UpdateOrderDetail.QotUpdateOrderDetail.S2C parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Qot_UpdateOrderDetail.QotUpdateOrderDetail.S2C parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Qot_UpdateOrderDetail.QotUpdateOrderDetail.S2C parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Qot_UpdateOrderDetail.QotUpdateOrderDetail.S2C parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Qot_UpdateOrderDetail.QotUpdateOrderDetail.S2C parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Qot_UpdateOrderDetail.QotUpdateOrderDetail.S2C parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Qot_UpdateOrderDetail.QotUpdateOrderDetail.S2C prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Qot_UpdateOrderDetail.S2C}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Qot_UpdateOrderDetail.S2C)
        Qot_UpdateOrderDetail.QotUpdateOrderDetail.S2COrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Qot_UpdateOrderDetail.QotUpdateOrderDetail.internal_static_Qot_UpdateOrderDetail_S2C_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Qot_UpdateOrderDetail.QotUpdateOrderDetail.internal_static_Qot_UpdateOrderDetail_S2C_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Qot_UpdateOrderDetail.QotUpdateOrderDetail.S2C.class, Qot_UpdateOrderDetail.QotUpdateOrderDetail.S2C.Builder.class);
      }

      // Construct using Qot_UpdateOrderDetail.QotUpdateOrderDetail.S2C.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getSecurityFieldBuilder();
          getOrderDetailAskFieldBuilder();
          getOrderDetailBidFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (securityBuilder_ == null) {
          security_ = null;
        } else {
          securityBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        if (orderDetailAskBuilder_ == null) {
          orderDetailAsk_ = null;
        } else {
          orderDetailAskBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        if (orderDetailBidBuilder_ == null) {
          orderDetailBid_ = null;
        } else {
          orderDetailBidBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Qot_UpdateOrderDetail.QotUpdateOrderDetail.internal_static_Qot_UpdateOrderDetail_S2C_descriptor;
      }

      @java.lang.Override
      public Qot_UpdateOrderDetail.QotUpdateOrderDetail.S2C getDefaultInstanceForType() {
        return Qot_UpdateOrderDetail.QotUpdateOrderDetail.S2C.getDefaultInstance();
      }

      @java.lang.Override
      public Qot_UpdateOrderDetail.QotUpdateOrderDetail.S2C build() {
        Qot_UpdateOrderDetail.QotUpdateOrderDetail.S2C result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public Qot_UpdateOrderDetail.QotUpdateOrderDetail.S2C buildPartial() {
        Qot_UpdateOrderDetail.QotUpdateOrderDetail.S2C result = new Qot_UpdateOrderDetail.QotUpdateOrderDetail.S2C(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          if (securityBuilder_ == null) {
            result.security_ = security_;
          } else {
            result.security_ = securityBuilder_.build();
          }
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          if (orderDetailAskBuilder_ == null) {
            result.orderDetailAsk_ = orderDetailAsk_;
          } else {
            result.orderDetailAsk_ = orderDetailAskBuilder_.build();
          }
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          if (orderDetailBidBuilder_ == null) {
            result.orderDetailBid_ = orderDetailBid_;
          } else {
            result.orderDetailBid_ = orderDetailBidBuilder_.build();
          }
          to_bitField0_ |= 0x00000004;
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Qot_UpdateOrderDetail.QotUpdateOrderDetail.S2C) {
          return mergeFrom((Qot_UpdateOrderDetail.QotUpdateOrderDetail.S2C)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Qot_UpdateOrderDetail.QotUpdateOrderDetail.S2C other) {
        if (other == Qot_UpdateOrderDetail.QotUpdateOrderDetail.S2C.getDefaultInstance()) return this;
        if (other.hasSecurity()) {
          mergeSecurity(other.getSecurity());
        }
        if (other.hasOrderDetailAsk()) {
          mergeOrderDetailAsk(other.getOrderDetailAsk());
        }
        if (other.hasOrderDetailBid()) {
          mergeOrderDetailBid(other.getOrderDetailBid());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasSecurity()) {
          return false;
        }
        if (!hasOrderDetailAsk()) {
          return false;
        }
        if (!hasOrderDetailBid()) {
          return false;
        }
        if (!getSecurity().isInitialized()) {
          return false;
        }
        if (!getOrderDetailAsk().isInitialized()) {
          return false;
        }
        if (!getOrderDetailBid().isInitialized()) {
          return false;
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Qot_UpdateOrderDetail.QotUpdateOrderDetail.S2C parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Qot_UpdateOrderDetail.QotUpdateOrderDetail.S2C) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private Qot_Common.QotCommon.Security security_;
      private com.google.protobuf.SingleFieldBuilderV3<
          Qot_Common.QotCommon.Security, Qot_Common.QotCommon.Security.Builder, Qot_Common.QotCommon.SecurityOrBuilder> securityBuilder_;
      /**
       * <pre>
       *股票
       * </pre>
       *
       * <code>required .Qot_Common.Security security = 1;</code>
       */
      public boolean hasSecurity() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <pre>
       *股票
       * </pre>
       *
       * <code>required .Qot_Common.Security security = 1;</code>
       */
      public Qot_Common.QotCommon.Security getSecurity() {
        if (securityBuilder_ == null) {
          return security_ == null ? Qot_Common.QotCommon.Security.getDefaultInstance() : security_;
        } else {
          return securityBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       *股票
       * </pre>
       *
       * <code>required .Qot_Common.Security security = 1;</code>
       */
      public Builder setSecurity(Qot_Common.QotCommon.Security value) {
        if (securityBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          security_ = value;
          onChanged();
        } else {
          securityBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <pre>
       *股票
       * </pre>
       *
       * <code>required .Qot_Common.Security security = 1;</code>
       */
      public Builder setSecurity(
          Qot_Common.QotCommon.Security.Builder builderForValue) {
        if (securityBuilder_ == null) {
          security_ = builderForValue.build();
          onChanged();
        } else {
          securityBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <pre>
       *股票
       * </pre>
       *
       * <code>required .Qot_Common.Security security = 1;</code>
       */
      public Builder mergeSecurity(Qot_Common.QotCommon.Security value) {
        if (securityBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0) &&
              security_ != null &&
              security_ != Qot_Common.QotCommon.Security.getDefaultInstance()) {
            security_ =
              Qot_Common.QotCommon.Security.newBuilder(security_).mergeFrom(value).buildPartial();
          } else {
            security_ = value;
          }
          onChanged();
        } else {
          securityBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <pre>
       *股票
       * </pre>
       *
       * <code>required .Qot_Common.Security security = 1;</code>
       */
      public Builder clearSecurity() {
        if (securityBuilder_ == null) {
          security_ = null;
          onChanged();
        } else {
          securityBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      /**
       * <pre>
       *股票
       * </pre>
       *
       * <code>required .Qot_Common.Security security = 1;</code>
       */
      public Qot_Common.QotCommon.Security.Builder getSecurityBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getSecurityFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       *股票
       * </pre>
       *
       * <code>required .Qot_Common.Security security = 1;</code>
       */
      public Qot_Common.QotCommon.SecurityOrBuilder getSecurityOrBuilder() {
        if (securityBuilder_ != null) {
          return securityBuilder_.getMessageOrBuilder();
        } else {
          return security_ == null ?
              Qot_Common.QotCommon.Security.getDefaultInstance() : security_;
        }
      }
      /**
       * <pre>
       *股票
       * </pre>
       *
       * <code>required .Qot_Common.Security security = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          Qot_Common.QotCommon.Security, Qot_Common.QotCommon.Security.Builder, Qot_Common.QotCommon.SecurityOrBuilder> 
          getSecurityFieldBuilder() {
        if (securityBuilder_ == null) {
          securityBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              Qot_Common.QotCommon.Security, Qot_Common.QotCommon.Security.Builder, Qot_Common.QotCommon.SecurityOrBuilder>(
                  getSecurity(),
                  getParentForChildren(),
                  isClean());
          security_ = null;
        }
        return securityBuilder_;
      }

      private Qot_Common.QotCommon.OrderDetail orderDetailAsk_;
      private com.google.protobuf.SingleFieldBuilderV3<
          Qot_Common.QotCommon.OrderDetail, Qot_Common.QotCommon.OrderDetail.Builder, Qot_Common.QotCommon.OrderDetailOrBuilder> orderDetailAskBuilder_;
      /**
       * <pre>
       *卖盘
       * </pre>
       *
       * <code>required .Qot_Common.OrderDetail orderDetailAsk = 2;</code>
       */
      public boolean hasOrderDetailAsk() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <pre>
       *卖盘
       * </pre>
       *
       * <code>required .Qot_Common.OrderDetail orderDetailAsk = 2;</code>
       */
      public Qot_Common.QotCommon.OrderDetail getOrderDetailAsk() {
        if (orderDetailAskBuilder_ == null) {
          return orderDetailAsk_ == null ? Qot_Common.QotCommon.OrderDetail.getDefaultInstance() : orderDetailAsk_;
        } else {
          return orderDetailAskBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       *卖盘
       * </pre>
       *
       * <code>required .Qot_Common.OrderDetail orderDetailAsk = 2;</code>
       */
      public Builder setOrderDetailAsk(Qot_Common.QotCommon.OrderDetail value) {
        if (orderDetailAskBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          orderDetailAsk_ = value;
          onChanged();
        } else {
          orderDetailAskBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <pre>
       *卖盘
       * </pre>
       *
       * <code>required .Qot_Common.OrderDetail orderDetailAsk = 2;</code>
       */
      public Builder setOrderDetailAsk(
          Qot_Common.QotCommon.OrderDetail.Builder builderForValue) {
        if (orderDetailAskBuilder_ == null) {
          orderDetailAsk_ = builderForValue.build();
          onChanged();
        } else {
          orderDetailAskBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <pre>
       *卖盘
       * </pre>
       *
       * <code>required .Qot_Common.OrderDetail orderDetailAsk = 2;</code>
       */
      public Builder mergeOrderDetailAsk(Qot_Common.QotCommon.OrderDetail value) {
        if (orderDetailAskBuilder_ == null) {
          if (((bitField0_ & 0x00000002) != 0) &&
              orderDetailAsk_ != null &&
              orderDetailAsk_ != Qot_Common.QotCommon.OrderDetail.getDefaultInstance()) {
            orderDetailAsk_ =
              Qot_Common.QotCommon.OrderDetail.newBuilder(orderDetailAsk_).mergeFrom(value).buildPartial();
          } else {
            orderDetailAsk_ = value;
          }
          onChanged();
        } else {
          orderDetailAskBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <pre>
       *卖盘
       * </pre>
       *
       * <code>required .Qot_Common.OrderDetail orderDetailAsk = 2;</code>
       */
      public Builder clearOrderDetailAsk() {
        if (orderDetailAskBuilder_ == null) {
          orderDetailAsk_ = null;
          onChanged();
        } else {
          orderDetailAskBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      /**
       * <pre>
       *卖盘
       * </pre>
       *
       * <code>required .Qot_Common.OrderDetail orderDetailAsk = 2;</code>
       */
      public Qot_Common.QotCommon.OrderDetail.Builder getOrderDetailAskBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getOrderDetailAskFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       *卖盘
       * </pre>
       *
       * <code>required .Qot_Common.OrderDetail orderDetailAsk = 2;</code>
       */
      public Qot_Common.QotCommon.OrderDetailOrBuilder getOrderDetailAskOrBuilder() {
        if (orderDetailAskBuilder_ != null) {
          return orderDetailAskBuilder_.getMessageOrBuilder();
        } else {
          return orderDetailAsk_ == null ?
              Qot_Common.QotCommon.OrderDetail.getDefaultInstance() : orderDetailAsk_;
        }
      }
      /**
       * <pre>
       *卖盘
       * </pre>
       *
       * <code>required .Qot_Common.OrderDetail orderDetailAsk = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          Qot_Common.QotCommon.OrderDetail, Qot_Common.QotCommon.OrderDetail.Builder, Qot_Common.QotCommon.OrderDetailOrBuilder> 
          getOrderDetailAskFieldBuilder() {
        if (orderDetailAskBuilder_ == null) {
          orderDetailAskBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              Qot_Common.QotCommon.OrderDetail, Qot_Common.QotCommon.OrderDetail.Builder, Qot_Common.QotCommon.OrderDetailOrBuilder>(
                  getOrderDetailAsk(),
                  getParentForChildren(),
                  isClean());
          orderDetailAsk_ = null;
        }
        return orderDetailAskBuilder_;
      }

      private Qot_Common.QotCommon.OrderDetail orderDetailBid_;
      private com.google.protobuf.SingleFieldBuilderV3<
          Qot_Common.QotCommon.OrderDetail, Qot_Common.QotCommon.OrderDetail.Builder, Qot_Common.QotCommon.OrderDetailOrBuilder> orderDetailBidBuilder_;
      /**
       * <pre>
       *买盘
       * </pre>
       *
       * <code>required .Qot_Common.OrderDetail orderDetailBid = 3;</code>
       */
      public boolean hasOrderDetailBid() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <pre>
       *买盘
       * </pre>
       *
       * <code>required .Qot_Common.OrderDetail orderDetailBid = 3;</code>
       */
      public Qot_Common.QotCommon.OrderDetail getOrderDetailBid() {
        if (orderDetailBidBuilder_ == null) {
          return orderDetailBid_ == null ? Qot_Common.QotCommon.OrderDetail.getDefaultInstance() : orderDetailBid_;
        } else {
          return orderDetailBidBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       *买盘
       * </pre>
       *
       * <code>required .Qot_Common.OrderDetail orderDetailBid = 3;</code>
       */
      public Builder setOrderDetailBid(Qot_Common.QotCommon.OrderDetail value) {
        if (orderDetailBidBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          orderDetailBid_ = value;
          onChanged();
        } else {
          orderDetailBidBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <pre>
       *买盘
       * </pre>
       *
       * <code>required .Qot_Common.OrderDetail orderDetailBid = 3;</code>
       */
      public Builder setOrderDetailBid(
          Qot_Common.QotCommon.OrderDetail.Builder builderForValue) {
        if (orderDetailBidBuilder_ == null) {
          orderDetailBid_ = builderForValue.build();
          onChanged();
        } else {
          orderDetailBidBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <pre>
       *买盘
       * </pre>
       *
       * <code>required .Qot_Common.OrderDetail orderDetailBid = 3;</code>
       */
      public Builder mergeOrderDetailBid(Qot_Common.QotCommon.OrderDetail value) {
        if (orderDetailBidBuilder_ == null) {
          if (((bitField0_ & 0x00000004) != 0) &&
              orderDetailBid_ != null &&
              orderDetailBid_ != Qot_Common.QotCommon.OrderDetail.getDefaultInstance()) {
            orderDetailBid_ =
              Qot_Common.QotCommon.OrderDetail.newBuilder(orderDetailBid_).mergeFrom(value).buildPartial();
          } else {
            orderDetailBid_ = value;
          }
          onChanged();
        } else {
          orderDetailBidBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <pre>
       *买盘
       * </pre>
       *
       * <code>required .Qot_Common.OrderDetail orderDetailBid = 3;</code>
       */
      public Builder clearOrderDetailBid() {
        if (orderDetailBidBuilder_ == null) {
          orderDetailBid_ = null;
          onChanged();
        } else {
          orderDetailBidBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      /**
       * <pre>
       *买盘
       * </pre>
       *
       * <code>required .Qot_Common.OrderDetail orderDetailBid = 3;</code>
       */
      public Qot_Common.QotCommon.OrderDetail.Builder getOrderDetailBidBuilder() {
        bitField0_ |= 0x00000004;
        onChanged();
        return getOrderDetailBidFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       *买盘
       * </pre>
       *
       * <code>required .Qot_Common.OrderDetail orderDetailBid = 3;</code>
       */
      public Qot_Common.QotCommon.OrderDetailOrBuilder getOrderDetailBidOrBuilder() {
        if (orderDetailBidBuilder_ != null) {
          return orderDetailBidBuilder_.getMessageOrBuilder();
        } else {
          return orderDetailBid_ == null ?
              Qot_Common.QotCommon.OrderDetail.getDefaultInstance() : orderDetailBid_;
        }
      }
      /**
       * <pre>
       *买盘
       * </pre>
       *
       * <code>required .Qot_Common.OrderDetail orderDetailBid = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          Qot_Common.QotCommon.OrderDetail, Qot_Common.QotCommon.OrderDetail.Builder, Qot_Common.QotCommon.OrderDetailOrBuilder> 
          getOrderDetailBidFieldBuilder() {
        if (orderDetailBidBuilder_ == null) {
          orderDetailBidBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              Qot_Common.QotCommon.OrderDetail, Qot_Common.QotCommon.OrderDetail.Builder, Qot_Common.QotCommon.OrderDetailOrBuilder>(
                  getOrderDetailBid(),
                  getParentForChildren(),
                  isClean());
          orderDetailBid_ = null;
        }
        return orderDetailBidBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Qot_UpdateOrderDetail.S2C)
    }

    // @@protoc_insertion_point(class_scope:Qot_UpdateOrderDetail.S2C)
    private static final Qot_UpdateOrderDetail.QotUpdateOrderDetail.S2C DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Qot_UpdateOrderDetail.QotUpdateOrderDetail.S2C();
    }

    public static Qot_UpdateOrderDetail.QotUpdateOrderDetail.S2C getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<S2C>
        PARSER = new com.google.protobuf.AbstractParser<S2C>() {
      @java.lang.Override
      public S2C parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new S2C(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<S2C> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<S2C> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public Qot_UpdateOrderDetail.QotUpdateOrderDetail.S2C getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Qot_UpdateOrderDetail.Response)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *RetType,返回结果
     * </pre>
     *
     * <code>required int32 retType = 1 [default = -400];</code>
     */
    boolean hasRetType();
    /**
     * <pre>
     *RetType,返回结果
     * </pre>
     *
     * <code>required int32 retType = 1 [default = -400];</code>
     */
    int getRetType();

    /**
     * <code>optional string retMsg = 2;</code>
     */
    boolean hasRetMsg();
    /**
     * <code>optional string retMsg = 2;</code>
     */
    java.lang.String getRetMsg();
    /**
     * <code>optional string retMsg = 2;</code>
     */
    com.google.protobuf.ByteString
        getRetMsgBytes();

    /**
     * <code>optional int32 errCode = 3;</code>
     */
    boolean hasErrCode();
    /**
     * <code>optional int32 errCode = 3;</code>
     */
    int getErrCode();

    /**
     * <code>optional .Qot_UpdateOrderDetail.S2C s2c = 4;</code>
     */
    boolean hasS2C();
    /**
     * <code>optional .Qot_UpdateOrderDetail.S2C s2c = 4;</code>
     */
    Qot_UpdateOrderDetail.QotUpdateOrderDetail.S2C getS2C();
    /**
     * <code>optional .Qot_UpdateOrderDetail.S2C s2c = 4;</code>
     */
    Qot_UpdateOrderDetail.QotUpdateOrderDetail.S2COrBuilder getS2COrBuilder();
  }
  /**
   * Protobuf type {@code Qot_UpdateOrderDetail.Response}
   */
  public  static final class Response extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Qot_UpdateOrderDetail.Response)
      ResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Response.newBuilder() to construct.
    private Response(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Response() {
      retType_ = -400;
      retMsg_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Response(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              bitField0_ |= 0x00000001;
              retType_ = input.readInt32();
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              retMsg_ = bs;
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              errCode_ = input.readInt32();
              break;
            }
            case 34: {
              Qot_UpdateOrderDetail.QotUpdateOrderDetail.S2C.Builder subBuilder = null;
              if (((bitField0_ & 0x00000008) != 0)) {
                subBuilder = s2C_.toBuilder();
              }
              s2C_ = input.readMessage(Qot_UpdateOrderDetail.QotUpdateOrderDetail.S2C.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(s2C_);
                s2C_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000008;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Qot_UpdateOrderDetail.QotUpdateOrderDetail.internal_static_Qot_UpdateOrderDetail_Response_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Qot_UpdateOrderDetail.QotUpdateOrderDetail.internal_static_Qot_UpdateOrderDetail_Response_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Qot_UpdateOrderDetail.QotUpdateOrderDetail.Response.class, Qot_UpdateOrderDetail.QotUpdateOrderDetail.Response.Builder.class);
    }

    private int bitField0_;
    public static final int RETTYPE_FIELD_NUMBER = 1;
    private int retType_;
    /**
     * <pre>
     *RetType,返回结果
     * </pre>
     *
     * <code>required int32 retType = 1 [default = -400];</code>
     */
    public boolean hasRetType() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     *RetType,返回结果
     * </pre>
     *
     * <code>required int32 retType = 1 [default = -400];</code>
     */
    public int getRetType() {
      return retType_;
    }

    public static final int RETMSG_FIELD_NUMBER = 2;
    private volatile java.lang.Object retMsg_;
    /**
     * <code>optional string retMsg = 2;</code>
     */
    public boolean hasRetMsg() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional string retMsg = 2;</code>
     */
    public java.lang.String getRetMsg() {
      java.lang.Object ref = retMsg_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          retMsg_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string retMsg = 2;</code>
     */
    public com.google.protobuf.ByteString
        getRetMsgBytes() {
      java.lang.Object ref = retMsg_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        retMsg_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ERRCODE_FIELD_NUMBER = 3;
    private int errCode_;
    /**
     * <code>optional int32 errCode = 3;</code>
     */
    public boolean hasErrCode() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional int32 errCode = 3;</code>
     */
    public int getErrCode() {
      return errCode_;
    }

    public static final int S2C_FIELD_NUMBER = 4;
    private Qot_UpdateOrderDetail.QotUpdateOrderDetail.S2C s2C_;
    /**
     * <code>optional .Qot_UpdateOrderDetail.S2C s2c = 4;</code>
     */
    public boolean hasS2C() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>optional .Qot_UpdateOrderDetail.S2C s2c = 4;</code>
     */
    public Qot_UpdateOrderDetail.QotUpdateOrderDetail.S2C getS2C() {
      return s2C_ == null ? Qot_UpdateOrderDetail.QotUpdateOrderDetail.S2C.getDefaultInstance() : s2C_;
    }
    /**
     * <code>optional .Qot_UpdateOrderDetail.S2C s2c = 4;</code>
     */
    public Qot_UpdateOrderDetail.QotUpdateOrderDetail.S2COrBuilder getS2COrBuilder() {
      return s2C_ == null ? Qot_UpdateOrderDetail.QotUpdateOrderDetail.S2C.getDefaultInstance() : s2C_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasRetType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (hasS2C()) {
        if (!getS2C().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeInt32(1, retType_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, retMsg_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        output.writeInt32(3, errCode_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        output.writeMessage(4, getS2C());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, retType_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, retMsg_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, errCode_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, getS2C());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Qot_UpdateOrderDetail.QotUpdateOrderDetail.Response)) {
        return super.equals(obj);
      }
      Qot_UpdateOrderDetail.QotUpdateOrderDetail.Response other = (Qot_UpdateOrderDetail.QotUpdateOrderDetail.Response) obj;

      if (hasRetType() != other.hasRetType()) return false;
      if (hasRetType()) {
        if (getRetType()
            != other.getRetType()) return false;
      }
      if (hasRetMsg() != other.hasRetMsg()) return false;
      if (hasRetMsg()) {
        if (!getRetMsg()
            .equals(other.getRetMsg())) return false;
      }
      if (hasErrCode() != other.hasErrCode()) return false;
      if (hasErrCode()) {
        if (getErrCode()
            != other.getErrCode()) return false;
      }
      if (hasS2C() != other.hasS2C()) return false;
      if (hasS2C()) {
        if (!getS2C()
            .equals(other.getS2C())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasRetType()) {
        hash = (37 * hash) + RETTYPE_FIELD_NUMBER;
        hash = (53 * hash) + getRetType();
      }
      if (hasRetMsg()) {
        hash = (37 * hash) + RETMSG_FIELD_NUMBER;
        hash = (53 * hash) + getRetMsg().hashCode();
      }
      if (hasErrCode()) {
        hash = (37 * hash) + ERRCODE_FIELD_NUMBER;
        hash = (53 * hash) + getErrCode();
      }
      if (hasS2C()) {
        hash = (37 * hash) + S2C_FIELD_NUMBER;
        hash = (53 * hash) + getS2C().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Qot_UpdateOrderDetail.QotUpdateOrderDetail.Response parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Qot_UpdateOrderDetail.QotUpdateOrderDetail.Response parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Qot_UpdateOrderDetail.QotUpdateOrderDetail.Response parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Qot_UpdateOrderDetail.QotUpdateOrderDetail.Response parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Qot_UpdateOrderDetail.QotUpdateOrderDetail.Response parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Qot_UpdateOrderDetail.QotUpdateOrderDetail.Response parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Qot_UpdateOrderDetail.QotUpdateOrderDetail.Response parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Qot_UpdateOrderDetail.QotUpdateOrderDetail.Response parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Qot_UpdateOrderDetail.QotUpdateOrderDetail.Response parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Qot_UpdateOrderDetail.QotUpdateOrderDetail.Response parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Qot_UpdateOrderDetail.QotUpdateOrderDetail.Response parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Qot_UpdateOrderDetail.QotUpdateOrderDetail.Response parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Qot_UpdateOrderDetail.QotUpdateOrderDetail.Response prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Qot_UpdateOrderDetail.Response}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Qot_UpdateOrderDetail.Response)
        Qot_UpdateOrderDetail.QotUpdateOrderDetail.ResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Qot_UpdateOrderDetail.QotUpdateOrderDetail.internal_static_Qot_UpdateOrderDetail_Response_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Qot_UpdateOrderDetail.QotUpdateOrderDetail.internal_static_Qot_UpdateOrderDetail_Response_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Qot_UpdateOrderDetail.QotUpdateOrderDetail.Response.class, Qot_UpdateOrderDetail.QotUpdateOrderDetail.Response.Builder.class);
      }

      // Construct using Qot_UpdateOrderDetail.QotUpdateOrderDetail.Response.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getS2CFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        retType_ = -400;
        bitField0_ = (bitField0_ & ~0x00000001);
        retMsg_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        errCode_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        if (s2CBuilder_ == null) {
          s2C_ = null;
        } else {
          s2CBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Qot_UpdateOrderDetail.QotUpdateOrderDetail.internal_static_Qot_UpdateOrderDetail_Response_descriptor;
      }

      @java.lang.Override
      public Qot_UpdateOrderDetail.QotUpdateOrderDetail.Response getDefaultInstanceForType() {
        return Qot_UpdateOrderDetail.QotUpdateOrderDetail.Response.getDefaultInstance();
      }

      @java.lang.Override
      public Qot_UpdateOrderDetail.QotUpdateOrderDetail.Response build() {
        Qot_UpdateOrderDetail.QotUpdateOrderDetail.Response result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public Qot_UpdateOrderDetail.QotUpdateOrderDetail.Response buildPartial() {
        Qot_UpdateOrderDetail.QotUpdateOrderDetail.Response result = new Qot_UpdateOrderDetail.QotUpdateOrderDetail.Response(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          to_bitField0_ |= 0x00000001;
        }
        result.retType_ = retType_;
        if (((from_bitField0_ & 0x00000002) != 0)) {
          to_bitField0_ |= 0x00000002;
        }
        result.retMsg_ = retMsg_;
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.errCode_ = errCode_;
          to_bitField0_ |= 0x00000004;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          if (s2CBuilder_ == null) {
            result.s2C_ = s2C_;
          } else {
            result.s2C_ = s2CBuilder_.build();
          }
          to_bitField0_ |= 0x00000008;
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Qot_UpdateOrderDetail.QotUpdateOrderDetail.Response) {
          return mergeFrom((Qot_UpdateOrderDetail.QotUpdateOrderDetail.Response)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Qot_UpdateOrderDetail.QotUpdateOrderDetail.Response other) {
        if (other == Qot_UpdateOrderDetail.QotUpdateOrderDetail.Response.getDefaultInstance()) return this;
        if (other.hasRetType()) {
          setRetType(other.getRetType());
        }
        if (other.hasRetMsg()) {
          bitField0_ |= 0x00000002;
          retMsg_ = other.retMsg_;
          onChanged();
        }
        if (other.hasErrCode()) {
          setErrCode(other.getErrCode());
        }
        if (other.hasS2C()) {
          mergeS2C(other.getS2C());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasRetType()) {
          return false;
        }
        if (hasS2C()) {
          if (!getS2C().isInitialized()) {
            return false;
          }
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Qot_UpdateOrderDetail.QotUpdateOrderDetail.Response parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Qot_UpdateOrderDetail.QotUpdateOrderDetail.Response) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int retType_ = -400;
      /**
       * <pre>
       *RetType,返回结果
       * </pre>
       *
       * <code>required int32 retType = 1 [default = -400];</code>
       */
      public boolean hasRetType() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <pre>
       *RetType,返回结果
       * </pre>
       *
       * <code>required int32 retType = 1 [default = -400];</code>
       */
      public int getRetType() {
        return retType_;
      }
      /**
       * <pre>
       *RetType,返回结果
       * </pre>
       *
       * <code>required int32 retType = 1 [default = -400];</code>
       */
      public Builder setRetType(int value) {
        bitField0_ |= 0x00000001;
        retType_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *RetType,返回结果
       * </pre>
       *
       * <code>required int32 retType = 1 [default = -400];</code>
       */
      public Builder clearRetType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        retType_ = -400;
        onChanged();
        return this;
      }

      private java.lang.Object retMsg_ = "";
      /**
       * <code>optional string retMsg = 2;</code>
       */
      public boolean hasRetMsg() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>optional string retMsg = 2;</code>
       */
      public java.lang.String getRetMsg() {
        java.lang.Object ref = retMsg_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            retMsg_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string retMsg = 2;</code>
       */
      public com.google.protobuf.ByteString
          getRetMsgBytes() {
        java.lang.Object ref = retMsg_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          retMsg_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string retMsg = 2;</code>
       */
      public Builder setRetMsg(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        retMsg_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string retMsg = 2;</code>
       */
      public Builder clearRetMsg() {
        bitField0_ = (bitField0_ & ~0x00000002);
        retMsg_ = getDefaultInstance().getRetMsg();
        onChanged();
        return this;
      }
      /**
       * <code>optional string retMsg = 2;</code>
       */
      public Builder setRetMsgBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        retMsg_ = value;
        onChanged();
        return this;
      }

      private int errCode_ ;
      /**
       * <code>optional int32 errCode = 3;</code>
       */
      public boolean hasErrCode() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>optional int32 errCode = 3;</code>
       */
      public int getErrCode() {
        return errCode_;
      }
      /**
       * <code>optional int32 errCode = 3;</code>
       */
      public Builder setErrCode(int value) {
        bitField0_ |= 0x00000004;
        errCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 errCode = 3;</code>
       */
      public Builder clearErrCode() {
        bitField0_ = (bitField0_ & ~0x00000004);
        errCode_ = 0;
        onChanged();
        return this;
      }

      private Qot_UpdateOrderDetail.QotUpdateOrderDetail.S2C s2C_;
      private com.google.protobuf.SingleFieldBuilderV3<
          Qot_UpdateOrderDetail.QotUpdateOrderDetail.S2C, Qot_UpdateOrderDetail.QotUpdateOrderDetail.S2C.Builder, Qot_UpdateOrderDetail.QotUpdateOrderDetail.S2COrBuilder> s2CBuilder_;
      /**
       * <code>optional .Qot_UpdateOrderDetail.S2C s2c = 4;</code>
       */
      public boolean hasS2C() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <code>optional .Qot_UpdateOrderDetail.S2C s2c = 4;</code>
       */
      public Qot_UpdateOrderDetail.QotUpdateOrderDetail.S2C getS2C() {
        if (s2CBuilder_ == null) {
          return s2C_ == null ? Qot_UpdateOrderDetail.QotUpdateOrderDetail.S2C.getDefaultInstance() : s2C_;
        } else {
          return s2CBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .Qot_UpdateOrderDetail.S2C s2c = 4;</code>
       */
      public Builder setS2C(Qot_UpdateOrderDetail.QotUpdateOrderDetail.S2C value) {
        if (s2CBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          s2C_ = value;
          onChanged();
        } else {
          s2CBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <code>optional .Qot_UpdateOrderDetail.S2C s2c = 4;</code>
       */
      public Builder setS2C(
          Qot_UpdateOrderDetail.QotUpdateOrderDetail.S2C.Builder builderForValue) {
        if (s2CBuilder_ == null) {
          s2C_ = builderForValue.build();
          onChanged();
        } else {
          s2CBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <code>optional .Qot_UpdateOrderDetail.S2C s2c = 4;</code>
       */
      public Builder mergeS2C(Qot_UpdateOrderDetail.QotUpdateOrderDetail.S2C value) {
        if (s2CBuilder_ == null) {
          if (((bitField0_ & 0x00000008) != 0) &&
              s2C_ != null &&
              s2C_ != Qot_UpdateOrderDetail.QotUpdateOrderDetail.S2C.getDefaultInstance()) {
            s2C_ =
              Qot_UpdateOrderDetail.QotUpdateOrderDetail.S2C.newBuilder(s2C_).mergeFrom(value).buildPartial();
          } else {
            s2C_ = value;
          }
          onChanged();
        } else {
          s2CBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <code>optional .Qot_UpdateOrderDetail.S2C s2c = 4;</code>
       */
      public Builder clearS2C() {
        if (s2CBuilder_ == null) {
          s2C_ = null;
          onChanged();
        } else {
          s2CBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }
      /**
       * <code>optional .Qot_UpdateOrderDetail.S2C s2c = 4;</code>
       */
      public Qot_UpdateOrderDetail.QotUpdateOrderDetail.S2C.Builder getS2CBuilder() {
        bitField0_ |= 0x00000008;
        onChanged();
        return getS2CFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .Qot_UpdateOrderDetail.S2C s2c = 4;</code>
       */
      public Qot_UpdateOrderDetail.QotUpdateOrderDetail.S2COrBuilder getS2COrBuilder() {
        if (s2CBuilder_ != null) {
          return s2CBuilder_.getMessageOrBuilder();
        } else {
          return s2C_ == null ?
              Qot_UpdateOrderDetail.QotUpdateOrderDetail.S2C.getDefaultInstance() : s2C_;
        }
      }
      /**
       * <code>optional .Qot_UpdateOrderDetail.S2C s2c = 4;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          Qot_UpdateOrderDetail.QotUpdateOrderDetail.S2C, Qot_UpdateOrderDetail.QotUpdateOrderDetail.S2C.Builder, Qot_UpdateOrderDetail.QotUpdateOrderDetail.S2COrBuilder> 
          getS2CFieldBuilder() {
        if (s2CBuilder_ == null) {
          s2CBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              Qot_UpdateOrderDetail.QotUpdateOrderDetail.S2C, Qot_UpdateOrderDetail.QotUpdateOrderDetail.S2C.Builder, Qot_UpdateOrderDetail.QotUpdateOrderDetail.S2COrBuilder>(
                  getS2C(),
                  getParentForChildren(),
                  isClean());
          s2C_ = null;
        }
        return s2CBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Qot_UpdateOrderDetail.Response)
    }

    // @@protoc_insertion_point(class_scope:Qot_UpdateOrderDetail.Response)
    private static final Qot_UpdateOrderDetail.QotUpdateOrderDetail.Response DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Qot_UpdateOrderDetail.QotUpdateOrderDetail.Response();
    }

    public static Qot_UpdateOrderDetail.QotUpdateOrderDetail.Response getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Response>
        PARSER = new com.google.protobuf.AbstractParser<Response>() {
      @java.lang.Override
      public Response parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Response(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Response> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Response> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public Qot_UpdateOrderDetail.QotUpdateOrderDetail.Response getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Qot_UpdateOrderDetail_S2C_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Qot_UpdateOrderDetail_S2C_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Qot_UpdateOrderDetail_Response_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Qot_UpdateOrderDetail_Response_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\033Qot_UpdateOrderDetail.proto\022\025Qot_Updat" +
      "eOrderDetail\032\014Common.proto\032\020Qot_Common.p" +
      "roto\"\217\001\n\003S2C\022&\n\010security\030\001 \002(\0132\024.Qot_Com" +
      "mon.Security\022/\n\016orderDetailAsk\030\002 \002(\0132\027.Q" +
      "ot_Common.OrderDetail\022/\n\016orderDetailBid\030" +
      "\003 \002(\0132\027.Qot_Common.OrderDetail\"k\n\010Respon" +
      "se\022\025\n\007retType\030\001 \002(\005:\004-400\022\016\n\006retMsg\030\002 \001(" +
      "\t\022\017\n\007errCode\030\003 \001(\005\022\'\n\003s2c\030\004 \001(\0132\032.Qot_Up" +
      "dateOrderDetail.S2C"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          Common.Common.getDescriptor(),
          Qot_Common.QotCommon.getDescriptor(),
        }, assigner);
    internal_static_Qot_UpdateOrderDetail_S2C_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Qot_UpdateOrderDetail_S2C_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Qot_UpdateOrderDetail_S2C_descriptor,
        new java.lang.String[] { "Security", "OrderDetailAsk", "OrderDetailBid", });
    internal_static_Qot_UpdateOrderDetail_Response_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Qot_UpdateOrderDetail_Response_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Qot_UpdateOrderDetail_Response_descriptor,
        new java.lang.String[] { "RetType", "RetMsg", "ErrCode", "S2C", });
    Common.Common.getDescriptor();
    Qot_Common.QotCommon.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
