// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Qot_UpdateOrderBook.proto

package Qot_UpdateOrderBook;

public final class QotUpdateOrderBook {
  private QotUpdateOrderBook() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface S2COrBuilder extends
      // @@protoc_insertion_point(interface_extends:Qot_UpdateOrderBook.S2C)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *股票
     * </pre>
     *
     * <code>required .Qot_Common.Security security = 1;</code>
     */
    boolean hasSecurity();
    /**
     * <pre>
     *股票
     * </pre>
     *
     * <code>required .Qot_Common.Security security = 1;</code>
     */
    Qot_Common.QotCommon.Security getSecurity();
    /**
     * <pre>
     *股票
     * </pre>
     *
     * <code>required .Qot_Common.Security security = 1;</code>
     */
    Qot_Common.QotCommon.SecurityOrBuilder getSecurityOrBuilder();

    /**
     * <pre>
     *卖盘
     * </pre>
     *
     * <code>repeated .Qot_Common.OrderBook orderBookAskList = 2;</code>
     */
    java.util.List<Qot_Common.QotCommon.OrderBook> 
        getOrderBookAskListList();
    /**
     * <pre>
     *卖盘
     * </pre>
     *
     * <code>repeated .Qot_Common.OrderBook orderBookAskList = 2;</code>
     */
    Qot_Common.QotCommon.OrderBook getOrderBookAskList(int index);
    /**
     * <pre>
     *卖盘
     * </pre>
     *
     * <code>repeated .Qot_Common.OrderBook orderBookAskList = 2;</code>
     */
    int getOrderBookAskListCount();
    /**
     * <pre>
     *卖盘
     * </pre>
     *
     * <code>repeated .Qot_Common.OrderBook orderBookAskList = 2;</code>
     */
    java.util.List<? extends Qot_Common.QotCommon.OrderBookOrBuilder> 
        getOrderBookAskListOrBuilderList();
    /**
     * <pre>
     *卖盘
     * </pre>
     *
     * <code>repeated .Qot_Common.OrderBook orderBookAskList = 2;</code>
     */
    Qot_Common.QotCommon.OrderBookOrBuilder getOrderBookAskListOrBuilder(
        int index);

    /**
     * <pre>
     *买盘
     * </pre>
     *
     * <code>repeated .Qot_Common.OrderBook orderBookBidList = 3;</code>
     */
    java.util.List<Qot_Common.QotCommon.OrderBook> 
        getOrderBookBidListList();
    /**
     * <pre>
     *买盘
     * </pre>
     *
     * <code>repeated .Qot_Common.OrderBook orderBookBidList = 3;</code>
     */
    Qot_Common.QotCommon.OrderBook getOrderBookBidList(int index);
    /**
     * <pre>
     *买盘
     * </pre>
     *
     * <code>repeated .Qot_Common.OrderBook orderBookBidList = 3;</code>
     */
    int getOrderBookBidListCount();
    /**
     * <pre>
     *买盘
     * </pre>
     *
     * <code>repeated .Qot_Common.OrderBook orderBookBidList = 3;</code>
     */
    java.util.List<? extends Qot_Common.QotCommon.OrderBookOrBuilder> 
        getOrderBookBidListOrBuilderList();
    /**
     * <pre>
     *买盘
     * </pre>
     *
     * <code>repeated .Qot_Common.OrderBook orderBookBidList = 3;</code>
     */
    Qot_Common.QotCommon.OrderBookOrBuilder getOrderBookBidListOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code Qot_UpdateOrderBook.S2C}
   */
  public  static final class S2C extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Qot_UpdateOrderBook.S2C)
      S2COrBuilder {
  private static final long serialVersionUID = 0L;
    // Use S2C.newBuilder() to construct.
    private S2C(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private S2C() {
      orderBookAskList_ = java.util.Collections.emptyList();
      orderBookBidList_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private S2C(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              Qot_Common.QotCommon.Security.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) != 0)) {
                subBuilder = security_.toBuilder();
              }
              security_ = input.readMessage(Qot_Common.QotCommon.Security.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(security_);
                security_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) != 0)) {
                orderBookAskList_ = new java.util.ArrayList<Qot_Common.QotCommon.OrderBook>();
                mutable_bitField0_ |= 0x00000002;
              }
              orderBookAskList_.add(
                  input.readMessage(Qot_Common.QotCommon.OrderBook.PARSER, extensionRegistry));
              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000004) != 0)) {
                orderBookBidList_ = new java.util.ArrayList<Qot_Common.QotCommon.OrderBook>();
                mutable_bitField0_ |= 0x00000004;
              }
              orderBookBidList_.add(
                  input.readMessage(Qot_Common.QotCommon.OrderBook.PARSER, extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) != 0)) {
          orderBookAskList_ = java.util.Collections.unmodifiableList(orderBookAskList_);
        }
        if (((mutable_bitField0_ & 0x00000004) != 0)) {
          orderBookBidList_ = java.util.Collections.unmodifiableList(orderBookBidList_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Qot_UpdateOrderBook.QotUpdateOrderBook.internal_static_Qot_UpdateOrderBook_S2C_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Qot_UpdateOrderBook.QotUpdateOrderBook.internal_static_Qot_UpdateOrderBook_S2C_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Qot_UpdateOrderBook.QotUpdateOrderBook.S2C.class, Qot_UpdateOrderBook.QotUpdateOrderBook.S2C.Builder.class);
    }

    private int bitField0_;
    public static final int SECURITY_FIELD_NUMBER = 1;
    private Qot_Common.QotCommon.Security security_;
    /**
     * <pre>
     *股票
     * </pre>
     *
     * <code>required .Qot_Common.Security security = 1;</code>
     */
    public boolean hasSecurity() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     *股票
     * </pre>
     *
     * <code>required .Qot_Common.Security security = 1;</code>
     */
    public Qot_Common.QotCommon.Security getSecurity() {
      return security_ == null ? Qot_Common.QotCommon.Security.getDefaultInstance() : security_;
    }
    /**
     * <pre>
     *股票
     * </pre>
     *
     * <code>required .Qot_Common.Security security = 1;</code>
     */
    public Qot_Common.QotCommon.SecurityOrBuilder getSecurityOrBuilder() {
      return security_ == null ? Qot_Common.QotCommon.Security.getDefaultInstance() : security_;
    }

    public static final int ORDERBOOKASKLIST_FIELD_NUMBER = 2;
    private java.util.List<Qot_Common.QotCommon.OrderBook> orderBookAskList_;
    /**
     * <pre>
     *卖盘
     * </pre>
     *
     * <code>repeated .Qot_Common.OrderBook orderBookAskList = 2;</code>
     */
    public java.util.List<Qot_Common.QotCommon.OrderBook> getOrderBookAskListList() {
      return orderBookAskList_;
    }
    /**
     * <pre>
     *卖盘
     * </pre>
     *
     * <code>repeated .Qot_Common.OrderBook orderBookAskList = 2;</code>
     */
    public java.util.List<? extends Qot_Common.QotCommon.OrderBookOrBuilder> 
        getOrderBookAskListOrBuilderList() {
      return orderBookAskList_;
    }
    /**
     * <pre>
     *卖盘
     * </pre>
     *
     * <code>repeated .Qot_Common.OrderBook orderBookAskList = 2;</code>
     */
    public int getOrderBookAskListCount() {
      return orderBookAskList_.size();
    }
    /**
     * <pre>
     *卖盘
     * </pre>
     *
     * <code>repeated .Qot_Common.OrderBook orderBookAskList = 2;</code>
     */
    public Qot_Common.QotCommon.OrderBook getOrderBookAskList(int index) {
      return orderBookAskList_.get(index);
    }
    /**
     * <pre>
     *卖盘
     * </pre>
     *
     * <code>repeated .Qot_Common.OrderBook orderBookAskList = 2;</code>
     */
    public Qot_Common.QotCommon.OrderBookOrBuilder getOrderBookAskListOrBuilder(
        int index) {
      return orderBookAskList_.get(index);
    }

    public static final int ORDERBOOKBIDLIST_FIELD_NUMBER = 3;
    private java.util.List<Qot_Common.QotCommon.OrderBook> orderBookBidList_;
    /**
     * <pre>
     *买盘
     * </pre>
     *
     * <code>repeated .Qot_Common.OrderBook orderBookBidList = 3;</code>
     */
    public java.util.List<Qot_Common.QotCommon.OrderBook> getOrderBookBidListList() {
      return orderBookBidList_;
    }
    /**
     * <pre>
     *买盘
     * </pre>
     *
     * <code>repeated .Qot_Common.OrderBook orderBookBidList = 3;</code>
     */
    public java.util.List<? extends Qot_Common.QotCommon.OrderBookOrBuilder> 
        getOrderBookBidListOrBuilderList() {
      return orderBookBidList_;
    }
    /**
     * <pre>
     *买盘
     * </pre>
     *
     * <code>repeated .Qot_Common.OrderBook orderBookBidList = 3;</code>
     */
    public int getOrderBookBidListCount() {
      return orderBookBidList_.size();
    }
    /**
     * <pre>
     *买盘
     * </pre>
     *
     * <code>repeated .Qot_Common.OrderBook orderBookBidList = 3;</code>
     */
    public Qot_Common.QotCommon.OrderBook getOrderBookBidList(int index) {
      return orderBookBidList_.get(index);
    }
    /**
     * <pre>
     *买盘
     * </pre>
     *
     * <code>repeated .Qot_Common.OrderBook orderBookBidList = 3;</code>
     */
    public Qot_Common.QotCommon.OrderBookOrBuilder getOrderBookBidListOrBuilder(
        int index) {
      return orderBookBidList_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasSecurity()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getSecurity().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getOrderBookAskListCount(); i++) {
        if (!getOrderBookAskList(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      for (int i = 0; i < getOrderBookBidListCount(); i++) {
        if (!getOrderBookBidList(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeMessage(1, getSecurity());
      }
      for (int i = 0; i < orderBookAskList_.size(); i++) {
        output.writeMessage(2, orderBookAskList_.get(i));
      }
      for (int i = 0; i < orderBookBidList_.size(); i++) {
        output.writeMessage(3, orderBookBidList_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getSecurity());
      }
      for (int i = 0; i < orderBookAskList_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, orderBookAskList_.get(i));
      }
      for (int i = 0; i < orderBookBidList_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, orderBookBidList_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Qot_UpdateOrderBook.QotUpdateOrderBook.S2C)) {
        return super.equals(obj);
      }
      Qot_UpdateOrderBook.QotUpdateOrderBook.S2C other = (Qot_UpdateOrderBook.QotUpdateOrderBook.S2C) obj;

      if (hasSecurity() != other.hasSecurity()) return false;
      if (hasSecurity()) {
        if (!getSecurity()
            .equals(other.getSecurity())) return false;
      }
      if (!getOrderBookAskListList()
          .equals(other.getOrderBookAskListList())) return false;
      if (!getOrderBookBidListList()
          .equals(other.getOrderBookBidListList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasSecurity()) {
        hash = (37 * hash) + SECURITY_FIELD_NUMBER;
        hash = (53 * hash) + getSecurity().hashCode();
      }
      if (getOrderBookAskListCount() > 0) {
        hash = (37 * hash) + ORDERBOOKASKLIST_FIELD_NUMBER;
        hash = (53 * hash) + getOrderBookAskListList().hashCode();
      }
      if (getOrderBookBidListCount() > 0) {
        hash = (37 * hash) + ORDERBOOKBIDLIST_FIELD_NUMBER;
        hash = (53 * hash) + getOrderBookBidListList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Qot_UpdateOrderBook.QotUpdateOrderBook.S2C parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Qot_UpdateOrderBook.QotUpdateOrderBook.S2C parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Qot_UpdateOrderBook.QotUpdateOrderBook.S2C parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Qot_UpdateOrderBook.QotUpdateOrderBook.S2C parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Qot_UpdateOrderBook.QotUpdateOrderBook.S2C parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Qot_UpdateOrderBook.QotUpdateOrderBook.S2C parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Qot_UpdateOrderBook.QotUpdateOrderBook.S2C parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Qot_UpdateOrderBook.QotUpdateOrderBook.S2C parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Qot_UpdateOrderBook.QotUpdateOrderBook.S2C parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Qot_UpdateOrderBook.QotUpdateOrderBook.S2C parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Qot_UpdateOrderBook.QotUpdateOrderBook.S2C parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Qot_UpdateOrderBook.QotUpdateOrderBook.S2C parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Qot_UpdateOrderBook.QotUpdateOrderBook.S2C prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Qot_UpdateOrderBook.S2C}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Qot_UpdateOrderBook.S2C)
        Qot_UpdateOrderBook.QotUpdateOrderBook.S2COrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Qot_UpdateOrderBook.QotUpdateOrderBook.internal_static_Qot_UpdateOrderBook_S2C_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Qot_UpdateOrderBook.QotUpdateOrderBook.internal_static_Qot_UpdateOrderBook_S2C_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Qot_UpdateOrderBook.QotUpdateOrderBook.S2C.class, Qot_UpdateOrderBook.QotUpdateOrderBook.S2C.Builder.class);
      }

      // Construct using Qot_UpdateOrderBook.QotUpdateOrderBook.S2C.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getSecurityFieldBuilder();
          getOrderBookAskListFieldBuilder();
          getOrderBookBidListFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (securityBuilder_ == null) {
          security_ = null;
        } else {
          securityBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        if (orderBookAskListBuilder_ == null) {
          orderBookAskList_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          orderBookAskListBuilder_.clear();
        }
        if (orderBookBidListBuilder_ == null) {
          orderBookBidList_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          orderBookBidListBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Qot_UpdateOrderBook.QotUpdateOrderBook.internal_static_Qot_UpdateOrderBook_S2C_descriptor;
      }

      @java.lang.Override
      public Qot_UpdateOrderBook.QotUpdateOrderBook.S2C getDefaultInstanceForType() {
        return Qot_UpdateOrderBook.QotUpdateOrderBook.S2C.getDefaultInstance();
      }

      @java.lang.Override
      public Qot_UpdateOrderBook.QotUpdateOrderBook.S2C build() {
        Qot_UpdateOrderBook.QotUpdateOrderBook.S2C result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public Qot_UpdateOrderBook.QotUpdateOrderBook.S2C buildPartial() {
        Qot_UpdateOrderBook.QotUpdateOrderBook.S2C result = new Qot_UpdateOrderBook.QotUpdateOrderBook.S2C(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          if (securityBuilder_ == null) {
            result.security_ = security_;
          } else {
            result.security_ = securityBuilder_.build();
          }
          to_bitField0_ |= 0x00000001;
        }
        if (orderBookAskListBuilder_ == null) {
          if (((bitField0_ & 0x00000002) != 0)) {
            orderBookAskList_ = java.util.Collections.unmodifiableList(orderBookAskList_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.orderBookAskList_ = orderBookAskList_;
        } else {
          result.orderBookAskList_ = orderBookAskListBuilder_.build();
        }
        if (orderBookBidListBuilder_ == null) {
          if (((bitField0_ & 0x00000004) != 0)) {
            orderBookBidList_ = java.util.Collections.unmodifiableList(orderBookBidList_);
            bitField0_ = (bitField0_ & ~0x00000004);
          }
          result.orderBookBidList_ = orderBookBidList_;
        } else {
          result.orderBookBidList_ = orderBookBidListBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Qot_UpdateOrderBook.QotUpdateOrderBook.S2C) {
          return mergeFrom((Qot_UpdateOrderBook.QotUpdateOrderBook.S2C)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Qot_UpdateOrderBook.QotUpdateOrderBook.S2C other) {
        if (other == Qot_UpdateOrderBook.QotUpdateOrderBook.S2C.getDefaultInstance()) return this;
        if (other.hasSecurity()) {
          mergeSecurity(other.getSecurity());
        }
        if (orderBookAskListBuilder_ == null) {
          if (!other.orderBookAskList_.isEmpty()) {
            if (orderBookAskList_.isEmpty()) {
              orderBookAskList_ = other.orderBookAskList_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureOrderBookAskListIsMutable();
              orderBookAskList_.addAll(other.orderBookAskList_);
            }
            onChanged();
          }
        } else {
          if (!other.orderBookAskList_.isEmpty()) {
            if (orderBookAskListBuilder_.isEmpty()) {
              orderBookAskListBuilder_.dispose();
              orderBookAskListBuilder_ = null;
              orderBookAskList_ = other.orderBookAskList_;
              bitField0_ = (bitField0_ & ~0x00000002);
              orderBookAskListBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getOrderBookAskListFieldBuilder() : null;
            } else {
              orderBookAskListBuilder_.addAllMessages(other.orderBookAskList_);
            }
          }
        }
        if (orderBookBidListBuilder_ == null) {
          if (!other.orderBookBidList_.isEmpty()) {
            if (orderBookBidList_.isEmpty()) {
              orderBookBidList_ = other.orderBookBidList_;
              bitField0_ = (bitField0_ & ~0x00000004);
            } else {
              ensureOrderBookBidListIsMutable();
              orderBookBidList_.addAll(other.orderBookBidList_);
            }
            onChanged();
          }
        } else {
          if (!other.orderBookBidList_.isEmpty()) {
            if (orderBookBidListBuilder_.isEmpty()) {
              orderBookBidListBuilder_.dispose();
              orderBookBidListBuilder_ = null;
              orderBookBidList_ = other.orderBookBidList_;
              bitField0_ = (bitField0_ & ~0x00000004);
              orderBookBidListBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getOrderBookBidListFieldBuilder() : null;
            } else {
              orderBookBidListBuilder_.addAllMessages(other.orderBookBidList_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasSecurity()) {
          return false;
        }
        if (!getSecurity().isInitialized()) {
          return false;
        }
        for (int i = 0; i < getOrderBookAskListCount(); i++) {
          if (!getOrderBookAskList(i).isInitialized()) {
            return false;
          }
        }
        for (int i = 0; i < getOrderBookBidListCount(); i++) {
          if (!getOrderBookBidList(i).isInitialized()) {
            return false;
          }
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Qot_UpdateOrderBook.QotUpdateOrderBook.S2C parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Qot_UpdateOrderBook.QotUpdateOrderBook.S2C) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private Qot_Common.QotCommon.Security security_;
      private com.google.protobuf.SingleFieldBuilderV3<
          Qot_Common.QotCommon.Security, Qot_Common.QotCommon.Security.Builder, Qot_Common.QotCommon.SecurityOrBuilder> securityBuilder_;
      /**
       * <pre>
       *股票
       * </pre>
       *
       * <code>required .Qot_Common.Security security = 1;</code>
       */
      public boolean hasSecurity() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <pre>
       *股票
       * </pre>
       *
       * <code>required .Qot_Common.Security security = 1;</code>
       */
      public Qot_Common.QotCommon.Security getSecurity() {
        if (securityBuilder_ == null) {
          return security_ == null ? Qot_Common.QotCommon.Security.getDefaultInstance() : security_;
        } else {
          return securityBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       *股票
       * </pre>
       *
       * <code>required .Qot_Common.Security security = 1;</code>
       */
      public Builder setSecurity(Qot_Common.QotCommon.Security value) {
        if (securityBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          security_ = value;
          onChanged();
        } else {
          securityBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <pre>
       *股票
       * </pre>
       *
       * <code>required .Qot_Common.Security security = 1;</code>
       */
      public Builder setSecurity(
          Qot_Common.QotCommon.Security.Builder builderForValue) {
        if (securityBuilder_ == null) {
          security_ = builderForValue.build();
          onChanged();
        } else {
          securityBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <pre>
       *股票
       * </pre>
       *
       * <code>required .Qot_Common.Security security = 1;</code>
       */
      public Builder mergeSecurity(Qot_Common.QotCommon.Security value) {
        if (securityBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0) &&
              security_ != null &&
              security_ != Qot_Common.QotCommon.Security.getDefaultInstance()) {
            security_ =
              Qot_Common.QotCommon.Security.newBuilder(security_).mergeFrom(value).buildPartial();
          } else {
            security_ = value;
          }
          onChanged();
        } else {
          securityBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <pre>
       *股票
       * </pre>
       *
       * <code>required .Qot_Common.Security security = 1;</code>
       */
      public Builder clearSecurity() {
        if (securityBuilder_ == null) {
          security_ = null;
          onChanged();
        } else {
          securityBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      /**
       * <pre>
       *股票
       * </pre>
       *
       * <code>required .Qot_Common.Security security = 1;</code>
       */
      public Qot_Common.QotCommon.Security.Builder getSecurityBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getSecurityFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       *股票
       * </pre>
       *
       * <code>required .Qot_Common.Security security = 1;</code>
       */
      public Qot_Common.QotCommon.SecurityOrBuilder getSecurityOrBuilder() {
        if (securityBuilder_ != null) {
          return securityBuilder_.getMessageOrBuilder();
        } else {
          return security_ == null ?
              Qot_Common.QotCommon.Security.getDefaultInstance() : security_;
        }
      }
      /**
       * <pre>
       *股票
       * </pre>
       *
       * <code>required .Qot_Common.Security security = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          Qot_Common.QotCommon.Security, Qot_Common.QotCommon.Security.Builder, Qot_Common.QotCommon.SecurityOrBuilder> 
          getSecurityFieldBuilder() {
        if (securityBuilder_ == null) {
          securityBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              Qot_Common.QotCommon.Security, Qot_Common.QotCommon.Security.Builder, Qot_Common.QotCommon.SecurityOrBuilder>(
                  getSecurity(),
                  getParentForChildren(),
                  isClean());
          security_ = null;
        }
        return securityBuilder_;
      }

      private java.util.List<Qot_Common.QotCommon.OrderBook> orderBookAskList_ =
        java.util.Collections.emptyList();
      private void ensureOrderBookAskListIsMutable() {
        if (!((bitField0_ & 0x00000002) != 0)) {
          orderBookAskList_ = new java.util.ArrayList<Qot_Common.QotCommon.OrderBook>(orderBookAskList_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          Qot_Common.QotCommon.OrderBook, Qot_Common.QotCommon.OrderBook.Builder, Qot_Common.QotCommon.OrderBookOrBuilder> orderBookAskListBuilder_;

      /**
       * <pre>
       *卖盘
       * </pre>
       *
       * <code>repeated .Qot_Common.OrderBook orderBookAskList = 2;</code>
       */
      public java.util.List<Qot_Common.QotCommon.OrderBook> getOrderBookAskListList() {
        if (orderBookAskListBuilder_ == null) {
          return java.util.Collections.unmodifiableList(orderBookAskList_);
        } else {
          return orderBookAskListBuilder_.getMessageList();
        }
      }
      /**
       * <pre>
       *卖盘
       * </pre>
       *
       * <code>repeated .Qot_Common.OrderBook orderBookAskList = 2;</code>
       */
      public int getOrderBookAskListCount() {
        if (orderBookAskListBuilder_ == null) {
          return orderBookAskList_.size();
        } else {
          return orderBookAskListBuilder_.getCount();
        }
      }
      /**
       * <pre>
       *卖盘
       * </pre>
       *
       * <code>repeated .Qot_Common.OrderBook orderBookAskList = 2;</code>
       */
      public Qot_Common.QotCommon.OrderBook getOrderBookAskList(int index) {
        if (orderBookAskListBuilder_ == null) {
          return orderBookAskList_.get(index);
        } else {
          return orderBookAskListBuilder_.getMessage(index);
        }
      }
      /**
       * <pre>
       *卖盘
       * </pre>
       *
       * <code>repeated .Qot_Common.OrderBook orderBookAskList = 2;</code>
       */
      public Builder setOrderBookAskList(
          int index, Qot_Common.QotCommon.OrderBook value) {
        if (orderBookAskListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureOrderBookAskListIsMutable();
          orderBookAskList_.set(index, value);
          onChanged();
        } else {
          orderBookAskListBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       *卖盘
       * </pre>
       *
       * <code>repeated .Qot_Common.OrderBook orderBookAskList = 2;</code>
       */
      public Builder setOrderBookAskList(
          int index, Qot_Common.QotCommon.OrderBook.Builder builderForValue) {
        if (orderBookAskListBuilder_ == null) {
          ensureOrderBookAskListIsMutable();
          orderBookAskList_.set(index, builderForValue.build());
          onChanged();
        } else {
          orderBookAskListBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       *卖盘
       * </pre>
       *
       * <code>repeated .Qot_Common.OrderBook orderBookAskList = 2;</code>
       */
      public Builder addOrderBookAskList(Qot_Common.QotCommon.OrderBook value) {
        if (orderBookAskListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureOrderBookAskListIsMutable();
          orderBookAskList_.add(value);
          onChanged();
        } else {
          orderBookAskListBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <pre>
       *卖盘
       * </pre>
       *
       * <code>repeated .Qot_Common.OrderBook orderBookAskList = 2;</code>
       */
      public Builder addOrderBookAskList(
          int index, Qot_Common.QotCommon.OrderBook value) {
        if (orderBookAskListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureOrderBookAskListIsMutable();
          orderBookAskList_.add(index, value);
          onChanged();
        } else {
          orderBookAskListBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       *卖盘
       * </pre>
       *
       * <code>repeated .Qot_Common.OrderBook orderBookAskList = 2;</code>
       */
      public Builder addOrderBookAskList(
          Qot_Common.QotCommon.OrderBook.Builder builderForValue) {
        if (orderBookAskListBuilder_ == null) {
          ensureOrderBookAskListIsMutable();
          orderBookAskList_.add(builderForValue.build());
          onChanged();
        } else {
          orderBookAskListBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       *卖盘
       * </pre>
       *
       * <code>repeated .Qot_Common.OrderBook orderBookAskList = 2;</code>
       */
      public Builder addOrderBookAskList(
          int index, Qot_Common.QotCommon.OrderBook.Builder builderForValue) {
        if (orderBookAskListBuilder_ == null) {
          ensureOrderBookAskListIsMutable();
          orderBookAskList_.add(index, builderForValue.build());
          onChanged();
        } else {
          orderBookAskListBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       *卖盘
       * </pre>
       *
       * <code>repeated .Qot_Common.OrderBook orderBookAskList = 2;</code>
       */
      public Builder addAllOrderBookAskList(
          java.lang.Iterable<? extends Qot_Common.QotCommon.OrderBook> values) {
        if (orderBookAskListBuilder_ == null) {
          ensureOrderBookAskListIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, orderBookAskList_);
          onChanged();
        } else {
          orderBookAskListBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <pre>
       *卖盘
       * </pre>
       *
       * <code>repeated .Qot_Common.OrderBook orderBookAskList = 2;</code>
       */
      public Builder clearOrderBookAskList() {
        if (orderBookAskListBuilder_ == null) {
          orderBookAskList_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          orderBookAskListBuilder_.clear();
        }
        return this;
      }
      /**
       * <pre>
       *卖盘
       * </pre>
       *
       * <code>repeated .Qot_Common.OrderBook orderBookAskList = 2;</code>
       */
      public Builder removeOrderBookAskList(int index) {
        if (orderBookAskListBuilder_ == null) {
          ensureOrderBookAskListIsMutable();
          orderBookAskList_.remove(index);
          onChanged();
        } else {
          orderBookAskListBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <pre>
       *卖盘
       * </pre>
       *
       * <code>repeated .Qot_Common.OrderBook orderBookAskList = 2;</code>
       */
      public Qot_Common.QotCommon.OrderBook.Builder getOrderBookAskListBuilder(
          int index) {
        return getOrderBookAskListFieldBuilder().getBuilder(index);
      }
      /**
       * <pre>
       *卖盘
       * </pre>
       *
       * <code>repeated .Qot_Common.OrderBook orderBookAskList = 2;</code>
       */
      public Qot_Common.QotCommon.OrderBookOrBuilder getOrderBookAskListOrBuilder(
          int index) {
        if (orderBookAskListBuilder_ == null) {
          return orderBookAskList_.get(index);  } else {
          return orderBookAskListBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <pre>
       *卖盘
       * </pre>
       *
       * <code>repeated .Qot_Common.OrderBook orderBookAskList = 2;</code>
       */
      public java.util.List<? extends Qot_Common.QotCommon.OrderBookOrBuilder> 
           getOrderBookAskListOrBuilderList() {
        if (orderBookAskListBuilder_ != null) {
          return orderBookAskListBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(orderBookAskList_);
        }
      }
      /**
       * <pre>
       *卖盘
       * </pre>
       *
       * <code>repeated .Qot_Common.OrderBook orderBookAskList = 2;</code>
       */
      public Qot_Common.QotCommon.OrderBook.Builder addOrderBookAskListBuilder() {
        return getOrderBookAskListFieldBuilder().addBuilder(
            Qot_Common.QotCommon.OrderBook.getDefaultInstance());
      }
      /**
       * <pre>
       *卖盘
       * </pre>
       *
       * <code>repeated .Qot_Common.OrderBook orderBookAskList = 2;</code>
       */
      public Qot_Common.QotCommon.OrderBook.Builder addOrderBookAskListBuilder(
          int index) {
        return getOrderBookAskListFieldBuilder().addBuilder(
            index, Qot_Common.QotCommon.OrderBook.getDefaultInstance());
      }
      /**
       * <pre>
       *卖盘
       * </pre>
       *
       * <code>repeated .Qot_Common.OrderBook orderBookAskList = 2;</code>
       */
      public java.util.List<Qot_Common.QotCommon.OrderBook.Builder> 
           getOrderBookAskListBuilderList() {
        return getOrderBookAskListFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          Qot_Common.QotCommon.OrderBook, Qot_Common.QotCommon.OrderBook.Builder, Qot_Common.QotCommon.OrderBookOrBuilder> 
          getOrderBookAskListFieldBuilder() {
        if (orderBookAskListBuilder_ == null) {
          orderBookAskListBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              Qot_Common.QotCommon.OrderBook, Qot_Common.QotCommon.OrderBook.Builder, Qot_Common.QotCommon.OrderBookOrBuilder>(
                  orderBookAskList_,
                  ((bitField0_ & 0x00000002) != 0),
                  getParentForChildren(),
                  isClean());
          orderBookAskList_ = null;
        }
        return orderBookAskListBuilder_;
      }

      private java.util.List<Qot_Common.QotCommon.OrderBook> orderBookBidList_ =
        java.util.Collections.emptyList();
      private void ensureOrderBookBidListIsMutable() {
        if (!((bitField0_ & 0x00000004) != 0)) {
          orderBookBidList_ = new java.util.ArrayList<Qot_Common.QotCommon.OrderBook>(orderBookBidList_);
          bitField0_ |= 0x00000004;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          Qot_Common.QotCommon.OrderBook, Qot_Common.QotCommon.OrderBook.Builder, Qot_Common.QotCommon.OrderBookOrBuilder> orderBookBidListBuilder_;

      /**
       * <pre>
       *买盘
       * </pre>
       *
       * <code>repeated .Qot_Common.OrderBook orderBookBidList = 3;</code>
       */
      public java.util.List<Qot_Common.QotCommon.OrderBook> getOrderBookBidListList() {
        if (orderBookBidListBuilder_ == null) {
          return java.util.Collections.unmodifiableList(orderBookBidList_);
        } else {
          return orderBookBidListBuilder_.getMessageList();
        }
      }
      /**
       * <pre>
       *买盘
       * </pre>
       *
       * <code>repeated .Qot_Common.OrderBook orderBookBidList = 3;</code>
       */
      public int getOrderBookBidListCount() {
        if (orderBookBidListBuilder_ == null) {
          return orderBookBidList_.size();
        } else {
          return orderBookBidListBuilder_.getCount();
        }
      }
      /**
       * <pre>
       *买盘
       * </pre>
       *
       * <code>repeated .Qot_Common.OrderBook orderBookBidList = 3;</code>
       */
      public Qot_Common.QotCommon.OrderBook getOrderBookBidList(int index) {
        if (orderBookBidListBuilder_ == null) {
          return orderBookBidList_.get(index);
        } else {
          return orderBookBidListBuilder_.getMessage(index);
        }
      }
      /**
       * <pre>
       *买盘
       * </pre>
       *
       * <code>repeated .Qot_Common.OrderBook orderBookBidList = 3;</code>
       */
      public Builder setOrderBookBidList(
          int index, Qot_Common.QotCommon.OrderBook value) {
        if (orderBookBidListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureOrderBookBidListIsMutable();
          orderBookBidList_.set(index, value);
          onChanged();
        } else {
          orderBookBidListBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       *买盘
       * </pre>
       *
       * <code>repeated .Qot_Common.OrderBook orderBookBidList = 3;</code>
       */
      public Builder setOrderBookBidList(
          int index, Qot_Common.QotCommon.OrderBook.Builder builderForValue) {
        if (orderBookBidListBuilder_ == null) {
          ensureOrderBookBidListIsMutable();
          orderBookBidList_.set(index, builderForValue.build());
          onChanged();
        } else {
          orderBookBidListBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       *买盘
       * </pre>
       *
       * <code>repeated .Qot_Common.OrderBook orderBookBidList = 3;</code>
       */
      public Builder addOrderBookBidList(Qot_Common.QotCommon.OrderBook value) {
        if (orderBookBidListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureOrderBookBidListIsMutable();
          orderBookBidList_.add(value);
          onChanged();
        } else {
          orderBookBidListBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <pre>
       *买盘
       * </pre>
       *
       * <code>repeated .Qot_Common.OrderBook orderBookBidList = 3;</code>
       */
      public Builder addOrderBookBidList(
          int index, Qot_Common.QotCommon.OrderBook value) {
        if (orderBookBidListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureOrderBookBidListIsMutable();
          orderBookBidList_.add(index, value);
          onChanged();
        } else {
          orderBookBidListBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       *买盘
       * </pre>
       *
       * <code>repeated .Qot_Common.OrderBook orderBookBidList = 3;</code>
       */
      public Builder addOrderBookBidList(
          Qot_Common.QotCommon.OrderBook.Builder builderForValue) {
        if (orderBookBidListBuilder_ == null) {
          ensureOrderBookBidListIsMutable();
          orderBookBidList_.add(builderForValue.build());
          onChanged();
        } else {
          orderBookBidListBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       *买盘
       * </pre>
       *
       * <code>repeated .Qot_Common.OrderBook orderBookBidList = 3;</code>
       */
      public Builder addOrderBookBidList(
          int index, Qot_Common.QotCommon.OrderBook.Builder builderForValue) {
        if (orderBookBidListBuilder_ == null) {
          ensureOrderBookBidListIsMutable();
          orderBookBidList_.add(index, builderForValue.build());
          onChanged();
        } else {
          orderBookBidListBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       *买盘
       * </pre>
       *
       * <code>repeated .Qot_Common.OrderBook orderBookBidList = 3;</code>
       */
      public Builder addAllOrderBookBidList(
          java.lang.Iterable<? extends Qot_Common.QotCommon.OrderBook> values) {
        if (orderBookBidListBuilder_ == null) {
          ensureOrderBookBidListIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, orderBookBidList_);
          onChanged();
        } else {
          orderBookBidListBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <pre>
       *买盘
       * </pre>
       *
       * <code>repeated .Qot_Common.OrderBook orderBookBidList = 3;</code>
       */
      public Builder clearOrderBookBidList() {
        if (orderBookBidListBuilder_ == null) {
          orderBookBidList_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
          onChanged();
        } else {
          orderBookBidListBuilder_.clear();
        }
        return this;
      }
      /**
       * <pre>
       *买盘
       * </pre>
       *
       * <code>repeated .Qot_Common.OrderBook orderBookBidList = 3;</code>
       */
      public Builder removeOrderBookBidList(int index) {
        if (orderBookBidListBuilder_ == null) {
          ensureOrderBookBidListIsMutable();
          orderBookBidList_.remove(index);
          onChanged();
        } else {
          orderBookBidListBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <pre>
       *买盘
       * </pre>
       *
       * <code>repeated .Qot_Common.OrderBook orderBookBidList = 3;</code>
       */
      public Qot_Common.QotCommon.OrderBook.Builder getOrderBookBidListBuilder(
          int index) {
        return getOrderBookBidListFieldBuilder().getBuilder(index);
      }
      /**
       * <pre>
       *买盘
       * </pre>
       *
       * <code>repeated .Qot_Common.OrderBook orderBookBidList = 3;</code>
       */
      public Qot_Common.QotCommon.OrderBookOrBuilder getOrderBookBidListOrBuilder(
          int index) {
        if (orderBookBidListBuilder_ == null) {
          return orderBookBidList_.get(index);  } else {
          return orderBookBidListBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <pre>
       *买盘
       * </pre>
       *
       * <code>repeated .Qot_Common.OrderBook orderBookBidList = 3;</code>
       */
      public java.util.List<? extends Qot_Common.QotCommon.OrderBookOrBuilder> 
           getOrderBookBidListOrBuilderList() {
        if (orderBookBidListBuilder_ != null) {
          return orderBookBidListBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(orderBookBidList_);
        }
      }
      /**
       * <pre>
       *买盘
       * </pre>
       *
       * <code>repeated .Qot_Common.OrderBook orderBookBidList = 3;</code>
       */
      public Qot_Common.QotCommon.OrderBook.Builder addOrderBookBidListBuilder() {
        return getOrderBookBidListFieldBuilder().addBuilder(
            Qot_Common.QotCommon.OrderBook.getDefaultInstance());
      }
      /**
       * <pre>
       *买盘
       * </pre>
       *
       * <code>repeated .Qot_Common.OrderBook orderBookBidList = 3;</code>
       */
      public Qot_Common.QotCommon.OrderBook.Builder addOrderBookBidListBuilder(
          int index) {
        return getOrderBookBidListFieldBuilder().addBuilder(
            index, Qot_Common.QotCommon.OrderBook.getDefaultInstance());
      }
      /**
       * <pre>
       *买盘
       * </pre>
       *
       * <code>repeated .Qot_Common.OrderBook orderBookBidList = 3;</code>
       */
      public java.util.List<Qot_Common.QotCommon.OrderBook.Builder> 
           getOrderBookBidListBuilderList() {
        return getOrderBookBidListFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          Qot_Common.QotCommon.OrderBook, Qot_Common.QotCommon.OrderBook.Builder, Qot_Common.QotCommon.OrderBookOrBuilder> 
          getOrderBookBidListFieldBuilder() {
        if (orderBookBidListBuilder_ == null) {
          orderBookBidListBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              Qot_Common.QotCommon.OrderBook, Qot_Common.QotCommon.OrderBook.Builder, Qot_Common.QotCommon.OrderBookOrBuilder>(
                  orderBookBidList_,
                  ((bitField0_ & 0x00000004) != 0),
                  getParentForChildren(),
                  isClean());
          orderBookBidList_ = null;
        }
        return orderBookBidListBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Qot_UpdateOrderBook.S2C)
    }

    // @@protoc_insertion_point(class_scope:Qot_UpdateOrderBook.S2C)
    private static final Qot_UpdateOrderBook.QotUpdateOrderBook.S2C DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Qot_UpdateOrderBook.QotUpdateOrderBook.S2C();
    }

    public static Qot_UpdateOrderBook.QotUpdateOrderBook.S2C getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<S2C>
        PARSER = new com.google.protobuf.AbstractParser<S2C>() {
      @java.lang.Override
      public S2C parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new S2C(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<S2C> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<S2C> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public Qot_UpdateOrderBook.QotUpdateOrderBook.S2C getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Qot_UpdateOrderBook.Response)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *RetType,返回结果
     * </pre>
     *
     * <code>required int32 retType = 1 [default = -400];</code>
     */
    boolean hasRetType();
    /**
     * <pre>
     *RetType,返回结果
     * </pre>
     *
     * <code>required int32 retType = 1 [default = -400];</code>
     */
    int getRetType();

    /**
     * <code>optional string retMsg = 2;</code>
     */
    boolean hasRetMsg();
    /**
     * <code>optional string retMsg = 2;</code>
     */
    java.lang.String getRetMsg();
    /**
     * <code>optional string retMsg = 2;</code>
     */
    com.google.protobuf.ByteString
        getRetMsgBytes();

    /**
     * <code>optional int32 errCode = 3;</code>
     */
    boolean hasErrCode();
    /**
     * <code>optional int32 errCode = 3;</code>
     */
    int getErrCode();

    /**
     * <code>optional .Qot_UpdateOrderBook.S2C s2c = 4;</code>
     */
    boolean hasS2C();
    /**
     * <code>optional .Qot_UpdateOrderBook.S2C s2c = 4;</code>
     */
    Qot_UpdateOrderBook.QotUpdateOrderBook.S2C getS2C();
    /**
     * <code>optional .Qot_UpdateOrderBook.S2C s2c = 4;</code>
     */
    Qot_UpdateOrderBook.QotUpdateOrderBook.S2COrBuilder getS2COrBuilder();
  }
  /**
   * Protobuf type {@code Qot_UpdateOrderBook.Response}
   */
  public  static final class Response extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Qot_UpdateOrderBook.Response)
      ResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Response.newBuilder() to construct.
    private Response(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Response() {
      retType_ = -400;
      retMsg_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Response(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              bitField0_ |= 0x00000001;
              retType_ = input.readInt32();
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              retMsg_ = bs;
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              errCode_ = input.readInt32();
              break;
            }
            case 34: {
              Qot_UpdateOrderBook.QotUpdateOrderBook.S2C.Builder subBuilder = null;
              if (((bitField0_ & 0x00000008) != 0)) {
                subBuilder = s2C_.toBuilder();
              }
              s2C_ = input.readMessage(Qot_UpdateOrderBook.QotUpdateOrderBook.S2C.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(s2C_);
                s2C_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000008;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Qot_UpdateOrderBook.QotUpdateOrderBook.internal_static_Qot_UpdateOrderBook_Response_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Qot_UpdateOrderBook.QotUpdateOrderBook.internal_static_Qot_UpdateOrderBook_Response_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Qot_UpdateOrderBook.QotUpdateOrderBook.Response.class, Qot_UpdateOrderBook.QotUpdateOrderBook.Response.Builder.class);
    }

    private int bitField0_;
    public static final int RETTYPE_FIELD_NUMBER = 1;
    private int retType_;
    /**
     * <pre>
     *RetType,返回结果
     * </pre>
     *
     * <code>required int32 retType = 1 [default = -400];</code>
     */
    public boolean hasRetType() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     *RetType,返回结果
     * </pre>
     *
     * <code>required int32 retType = 1 [default = -400];</code>
     */
    public int getRetType() {
      return retType_;
    }

    public static final int RETMSG_FIELD_NUMBER = 2;
    private volatile java.lang.Object retMsg_;
    /**
     * <code>optional string retMsg = 2;</code>
     */
    public boolean hasRetMsg() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional string retMsg = 2;</code>
     */
    public java.lang.String getRetMsg() {
      java.lang.Object ref = retMsg_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          retMsg_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string retMsg = 2;</code>
     */
    public com.google.protobuf.ByteString
        getRetMsgBytes() {
      java.lang.Object ref = retMsg_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        retMsg_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ERRCODE_FIELD_NUMBER = 3;
    private int errCode_;
    /**
     * <code>optional int32 errCode = 3;</code>
     */
    public boolean hasErrCode() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional int32 errCode = 3;</code>
     */
    public int getErrCode() {
      return errCode_;
    }

    public static final int S2C_FIELD_NUMBER = 4;
    private Qot_UpdateOrderBook.QotUpdateOrderBook.S2C s2C_;
    /**
     * <code>optional .Qot_UpdateOrderBook.S2C s2c = 4;</code>
     */
    public boolean hasS2C() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>optional .Qot_UpdateOrderBook.S2C s2c = 4;</code>
     */
    public Qot_UpdateOrderBook.QotUpdateOrderBook.S2C getS2C() {
      return s2C_ == null ? Qot_UpdateOrderBook.QotUpdateOrderBook.S2C.getDefaultInstance() : s2C_;
    }
    /**
     * <code>optional .Qot_UpdateOrderBook.S2C s2c = 4;</code>
     */
    public Qot_UpdateOrderBook.QotUpdateOrderBook.S2COrBuilder getS2COrBuilder() {
      return s2C_ == null ? Qot_UpdateOrderBook.QotUpdateOrderBook.S2C.getDefaultInstance() : s2C_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasRetType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (hasS2C()) {
        if (!getS2C().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeInt32(1, retType_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, retMsg_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        output.writeInt32(3, errCode_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        output.writeMessage(4, getS2C());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, retType_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, retMsg_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, errCode_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, getS2C());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Qot_UpdateOrderBook.QotUpdateOrderBook.Response)) {
        return super.equals(obj);
      }
      Qot_UpdateOrderBook.QotUpdateOrderBook.Response other = (Qot_UpdateOrderBook.QotUpdateOrderBook.Response) obj;

      if (hasRetType() != other.hasRetType()) return false;
      if (hasRetType()) {
        if (getRetType()
            != other.getRetType()) return false;
      }
      if (hasRetMsg() != other.hasRetMsg()) return false;
      if (hasRetMsg()) {
        if (!getRetMsg()
            .equals(other.getRetMsg())) return false;
      }
      if (hasErrCode() != other.hasErrCode()) return false;
      if (hasErrCode()) {
        if (getErrCode()
            != other.getErrCode()) return false;
      }
      if (hasS2C() != other.hasS2C()) return false;
      if (hasS2C()) {
        if (!getS2C()
            .equals(other.getS2C())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasRetType()) {
        hash = (37 * hash) + RETTYPE_FIELD_NUMBER;
        hash = (53 * hash) + getRetType();
      }
      if (hasRetMsg()) {
        hash = (37 * hash) + RETMSG_FIELD_NUMBER;
        hash = (53 * hash) + getRetMsg().hashCode();
      }
      if (hasErrCode()) {
        hash = (37 * hash) + ERRCODE_FIELD_NUMBER;
        hash = (53 * hash) + getErrCode();
      }
      if (hasS2C()) {
        hash = (37 * hash) + S2C_FIELD_NUMBER;
        hash = (53 * hash) + getS2C().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Qot_UpdateOrderBook.QotUpdateOrderBook.Response parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Qot_UpdateOrderBook.QotUpdateOrderBook.Response parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Qot_UpdateOrderBook.QotUpdateOrderBook.Response parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Qot_UpdateOrderBook.QotUpdateOrderBook.Response parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Qot_UpdateOrderBook.QotUpdateOrderBook.Response parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Qot_UpdateOrderBook.QotUpdateOrderBook.Response parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Qot_UpdateOrderBook.QotUpdateOrderBook.Response parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Qot_UpdateOrderBook.QotUpdateOrderBook.Response parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Qot_UpdateOrderBook.QotUpdateOrderBook.Response parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Qot_UpdateOrderBook.QotUpdateOrderBook.Response parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Qot_UpdateOrderBook.QotUpdateOrderBook.Response parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Qot_UpdateOrderBook.QotUpdateOrderBook.Response parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Qot_UpdateOrderBook.QotUpdateOrderBook.Response prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Qot_UpdateOrderBook.Response}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Qot_UpdateOrderBook.Response)
        Qot_UpdateOrderBook.QotUpdateOrderBook.ResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Qot_UpdateOrderBook.QotUpdateOrderBook.internal_static_Qot_UpdateOrderBook_Response_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Qot_UpdateOrderBook.QotUpdateOrderBook.internal_static_Qot_UpdateOrderBook_Response_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Qot_UpdateOrderBook.QotUpdateOrderBook.Response.class, Qot_UpdateOrderBook.QotUpdateOrderBook.Response.Builder.class);
      }

      // Construct using Qot_UpdateOrderBook.QotUpdateOrderBook.Response.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getS2CFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        retType_ = -400;
        bitField0_ = (bitField0_ & ~0x00000001);
        retMsg_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        errCode_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        if (s2CBuilder_ == null) {
          s2C_ = null;
        } else {
          s2CBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Qot_UpdateOrderBook.QotUpdateOrderBook.internal_static_Qot_UpdateOrderBook_Response_descriptor;
      }

      @java.lang.Override
      public Qot_UpdateOrderBook.QotUpdateOrderBook.Response getDefaultInstanceForType() {
        return Qot_UpdateOrderBook.QotUpdateOrderBook.Response.getDefaultInstance();
      }

      @java.lang.Override
      public Qot_UpdateOrderBook.QotUpdateOrderBook.Response build() {
        Qot_UpdateOrderBook.QotUpdateOrderBook.Response result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public Qot_UpdateOrderBook.QotUpdateOrderBook.Response buildPartial() {
        Qot_UpdateOrderBook.QotUpdateOrderBook.Response result = new Qot_UpdateOrderBook.QotUpdateOrderBook.Response(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          to_bitField0_ |= 0x00000001;
        }
        result.retType_ = retType_;
        if (((from_bitField0_ & 0x00000002) != 0)) {
          to_bitField0_ |= 0x00000002;
        }
        result.retMsg_ = retMsg_;
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.errCode_ = errCode_;
          to_bitField0_ |= 0x00000004;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          if (s2CBuilder_ == null) {
            result.s2C_ = s2C_;
          } else {
            result.s2C_ = s2CBuilder_.build();
          }
          to_bitField0_ |= 0x00000008;
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Qot_UpdateOrderBook.QotUpdateOrderBook.Response) {
          return mergeFrom((Qot_UpdateOrderBook.QotUpdateOrderBook.Response)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Qot_UpdateOrderBook.QotUpdateOrderBook.Response other) {
        if (other == Qot_UpdateOrderBook.QotUpdateOrderBook.Response.getDefaultInstance()) return this;
        if (other.hasRetType()) {
          setRetType(other.getRetType());
        }
        if (other.hasRetMsg()) {
          bitField0_ |= 0x00000002;
          retMsg_ = other.retMsg_;
          onChanged();
        }
        if (other.hasErrCode()) {
          setErrCode(other.getErrCode());
        }
        if (other.hasS2C()) {
          mergeS2C(other.getS2C());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasRetType()) {
          return false;
        }
        if (hasS2C()) {
          if (!getS2C().isInitialized()) {
            return false;
          }
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Qot_UpdateOrderBook.QotUpdateOrderBook.Response parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Qot_UpdateOrderBook.QotUpdateOrderBook.Response) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int retType_ = -400;
      /**
       * <pre>
       *RetType,返回结果
       * </pre>
       *
       * <code>required int32 retType = 1 [default = -400];</code>
       */
      public boolean hasRetType() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <pre>
       *RetType,返回结果
       * </pre>
       *
       * <code>required int32 retType = 1 [default = -400];</code>
       */
      public int getRetType() {
        return retType_;
      }
      /**
       * <pre>
       *RetType,返回结果
       * </pre>
       *
       * <code>required int32 retType = 1 [default = -400];</code>
       */
      public Builder setRetType(int value) {
        bitField0_ |= 0x00000001;
        retType_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *RetType,返回结果
       * </pre>
       *
       * <code>required int32 retType = 1 [default = -400];</code>
       */
      public Builder clearRetType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        retType_ = -400;
        onChanged();
        return this;
      }

      private java.lang.Object retMsg_ = "";
      /**
       * <code>optional string retMsg = 2;</code>
       */
      public boolean hasRetMsg() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>optional string retMsg = 2;</code>
       */
      public java.lang.String getRetMsg() {
        java.lang.Object ref = retMsg_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            retMsg_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string retMsg = 2;</code>
       */
      public com.google.protobuf.ByteString
          getRetMsgBytes() {
        java.lang.Object ref = retMsg_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          retMsg_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string retMsg = 2;</code>
       */
      public Builder setRetMsg(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        retMsg_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string retMsg = 2;</code>
       */
      public Builder clearRetMsg() {
        bitField0_ = (bitField0_ & ~0x00000002);
        retMsg_ = getDefaultInstance().getRetMsg();
        onChanged();
        return this;
      }
      /**
       * <code>optional string retMsg = 2;</code>
       */
      public Builder setRetMsgBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        retMsg_ = value;
        onChanged();
        return this;
      }

      private int errCode_ ;
      /**
       * <code>optional int32 errCode = 3;</code>
       */
      public boolean hasErrCode() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>optional int32 errCode = 3;</code>
       */
      public int getErrCode() {
        return errCode_;
      }
      /**
       * <code>optional int32 errCode = 3;</code>
       */
      public Builder setErrCode(int value) {
        bitField0_ |= 0x00000004;
        errCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 errCode = 3;</code>
       */
      public Builder clearErrCode() {
        bitField0_ = (bitField0_ & ~0x00000004);
        errCode_ = 0;
        onChanged();
        return this;
      }

      private Qot_UpdateOrderBook.QotUpdateOrderBook.S2C s2C_;
      private com.google.protobuf.SingleFieldBuilderV3<
          Qot_UpdateOrderBook.QotUpdateOrderBook.S2C, Qot_UpdateOrderBook.QotUpdateOrderBook.S2C.Builder, Qot_UpdateOrderBook.QotUpdateOrderBook.S2COrBuilder> s2CBuilder_;
      /**
       * <code>optional .Qot_UpdateOrderBook.S2C s2c = 4;</code>
       */
      public boolean hasS2C() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <code>optional .Qot_UpdateOrderBook.S2C s2c = 4;</code>
       */
      public Qot_UpdateOrderBook.QotUpdateOrderBook.S2C getS2C() {
        if (s2CBuilder_ == null) {
          return s2C_ == null ? Qot_UpdateOrderBook.QotUpdateOrderBook.S2C.getDefaultInstance() : s2C_;
        } else {
          return s2CBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .Qot_UpdateOrderBook.S2C s2c = 4;</code>
       */
      public Builder setS2C(Qot_UpdateOrderBook.QotUpdateOrderBook.S2C value) {
        if (s2CBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          s2C_ = value;
          onChanged();
        } else {
          s2CBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <code>optional .Qot_UpdateOrderBook.S2C s2c = 4;</code>
       */
      public Builder setS2C(
          Qot_UpdateOrderBook.QotUpdateOrderBook.S2C.Builder builderForValue) {
        if (s2CBuilder_ == null) {
          s2C_ = builderForValue.build();
          onChanged();
        } else {
          s2CBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <code>optional .Qot_UpdateOrderBook.S2C s2c = 4;</code>
       */
      public Builder mergeS2C(Qot_UpdateOrderBook.QotUpdateOrderBook.S2C value) {
        if (s2CBuilder_ == null) {
          if (((bitField0_ & 0x00000008) != 0) &&
              s2C_ != null &&
              s2C_ != Qot_UpdateOrderBook.QotUpdateOrderBook.S2C.getDefaultInstance()) {
            s2C_ =
              Qot_UpdateOrderBook.QotUpdateOrderBook.S2C.newBuilder(s2C_).mergeFrom(value).buildPartial();
          } else {
            s2C_ = value;
          }
          onChanged();
        } else {
          s2CBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <code>optional .Qot_UpdateOrderBook.S2C s2c = 4;</code>
       */
      public Builder clearS2C() {
        if (s2CBuilder_ == null) {
          s2C_ = null;
          onChanged();
        } else {
          s2CBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }
      /**
       * <code>optional .Qot_UpdateOrderBook.S2C s2c = 4;</code>
       */
      public Qot_UpdateOrderBook.QotUpdateOrderBook.S2C.Builder getS2CBuilder() {
        bitField0_ |= 0x00000008;
        onChanged();
        return getS2CFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .Qot_UpdateOrderBook.S2C s2c = 4;</code>
       */
      public Qot_UpdateOrderBook.QotUpdateOrderBook.S2COrBuilder getS2COrBuilder() {
        if (s2CBuilder_ != null) {
          return s2CBuilder_.getMessageOrBuilder();
        } else {
          return s2C_ == null ?
              Qot_UpdateOrderBook.QotUpdateOrderBook.S2C.getDefaultInstance() : s2C_;
        }
      }
      /**
       * <code>optional .Qot_UpdateOrderBook.S2C s2c = 4;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          Qot_UpdateOrderBook.QotUpdateOrderBook.S2C, Qot_UpdateOrderBook.QotUpdateOrderBook.S2C.Builder, Qot_UpdateOrderBook.QotUpdateOrderBook.S2COrBuilder> 
          getS2CFieldBuilder() {
        if (s2CBuilder_ == null) {
          s2CBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              Qot_UpdateOrderBook.QotUpdateOrderBook.S2C, Qot_UpdateOrderBook.QotUpdateOrderBook.S2C.Builder, Qot_UpdateOrderBook.QotUpdateOrderBook.S2COrBuilder>(
                  getS2C(),
                  getParentForChildren(),
                  isClean());
          s2C_ = null;
        }
        return s2CBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Qot_UpdateOrderBook.Response)
    }

    // @@protoc_insertion_point(class_scope:Qot_UpdateOrderBook.Response)
    private static final Qot_UpdateOrderBook.QotUpdateOrderBook.Response DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Qot_UpdateOrderBook.QotUpdateOrderBook.Response();
    }

    public static Qot_UpdateOrderBook.QotUpdateOrderBook.Response getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Response>
        PARSER = new com.google.protobuf.AbstractParser<Response>() {
      @java.lang.Override
      public Response parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Response(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Response> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Response> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public Qot_UpdateOrderBook.QotUpdateOrderBook.Response getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Qot_UpdateOrderBook_S2C_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Qot_UpdateOrderBook_S2C_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Qot_UpdateOrderBook_Response_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Qot_UpdateOrderBook_Response_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\031Qot_UpdateOrderBook.proto\022\023Qot_UpdateO" +
      "rderBook\032\014Common.proto\032\020Qot_Common.proto" +
      "\"\217\001\n\003S2C\022&\n\010security\030\001 \002(\0132\024.Qot_Common." +
      "Security\022/\n\020orderBookAskList\030\002 \003(\0132\025.Qot" +
      "_Common.OrderBook\022/\n\020orderBookBidList\030\003 " +
      "\003(\0132\025.Qot_Common.OrderBook\"i\n\010Response\022\025" +
      "\n\007retType\030\001 \002(\005:\004-400\022\016\n\006retMsg\030\002 \001(\t\022\017\n" +
      "\007errCode\030\003 \001(\005\022%\n\003s2c\030\004 \001(\0132\030.Qot_Update" +
      "OrderBook.S2C"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          Common.Common.getDescriptor(),
          Qot_Common.QotCommon.getDescriptor(),
        }, assigner);
    internal_static_Qot_UpdateOrderBook_S2C_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Qot_UpdateOrderBook_S2C_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Qot_UpdateOrderBook_S2C_descriptor,
        new java.lang.String[] { "Security", "OrderBookAskList", "OrderBookBidList", });
    internal_static_Qot_UpdateOrderBook_Response_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Qot_UpdateOrderBook_Response_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Qot_UpdateOrderBook_Response_descriptor,
        new java.lang.String[] { "RetType", "RetMsg", "ErrCode", "S2C", });
    Common.Common.getDescriptor();
    Qot_Common.QotCommon.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
