// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Trd_UpdateOrder.proto

package Trd_UpdateOrder;

public final class TrdUpdateOrder {
  private TrdUpdateOrder() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface S2COrBuilder extends
      // @@protoc_insertion_point(interface_extends:Trd_UpdateOrder.S2C)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *交易公共参数头
     * </pre>
     *
     * <code>required .Trd_Common.TrdHeader header = 1;</code>
     */
    boolean hasHeader();
    /**
     * <pre>
     *交易公共参数头
     * </pre>
     *
     * <code>required .Trd_Common.TrdHeader header = 1;</code>
     */
    Trd_Common.TrdCommon.TrdHeader getHeader();
    /**
     * <pre>
     *交易公共参数头
     * </pre>
     *
     * <code>required .Trd_Common.TrdHeader header = 1;</code>
     */
    Trd_Common.TrdCommon.TrdHeaderOrBuilder getHeaderOrBuilder();

    /**
     * <pre>
     *订单结构
     * </pre>
     *
     * <code>required .Trd_Common.Order order = 2;</code>
     */
    boolean hasOrder();
    /**
     * <pre>
     *订单结构
     * </pre>
     *
     * <code>required .Trd_Common.Order order = 2;</code>
     */
    Trd_Common.TrdCommon.Order getOrder();
    /**
     * <pre>
     *订单结构
     * </pre>
     *
     * <code>required .Trd_Common.Order order = 2;</code>
     */
    Trd_Common.TrdCommon.OrderOrBuilder getOrderOrBuilder();
  }
  /**
   * Protobuf type {@code Trd_UpdateOrder.S2C}
   */
  public  static final class S2C extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Trd_UpdateOrder.S2C)
      S2COrBuilder {
  private static final long serialVersionUID = 0L;
    // Use S2C.newBuilder() to construct.
    private S2C(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private S2C() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private S2C(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              Trd_Common.TrdCommon.TrdHeader.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) != 0)) {
                subBuilder = header_.toBuilder();
              }
              header_ = input.readMessage(Trd_Common.TrdCommon.TrdHeader.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(header_);
                header_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
            case 18: {
              Trd_Common.TrdCommon.Order.Builder subBuilder = null;
              if (((bitField0_ & 0x00000002) != 0)) {
                subBuilder = order_.toBuilder();
              }
              order_ = input.readMessage(Trd_Common.TrdCommon.Order.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(order_);
                order_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000002;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Trd_UpdateOrder.TrdUpdateOrder.internal_static_Trd_UpdateOrder_S2C_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Trd_UpdateOrder.TrdUpdateOrder.internal_static_Trd_UpdateOrder_S2C_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Trd_UpdateOrder.TrdUpdateOrder.S2C.class, Trd_UpdateOrder.TrdUpdateOrder.S2C.Builder.class);
    }

    private int bitField0_;
    public static final int HEADER_FIELD_NUMBER = 1;
    private Trd_Common.TrdCommon.TrdHeader header_;
    /**
     * <pre>
     *交易公共参数头
     * </pre>
     *
     * <code>required .Trd_Common.TrdHeader header = 1;</code>
     */
    public boolean hasHeader() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     *交易公共参数头
     * </pre>
     *
     * <code>required .Trd_Common.TrdHeader header = 1;</code>
     */
    public Trd_Common.TrdCommon.TrdHeader getHeader() {
      return header_ == null ? Trd_Common.TrdCommon.TrdHeader.getDefaultInstance() : header_;
    }
    /**
     * <pre>
     *交易公共参数头
     * </pre>
     *
     * <code>required .Trd_Common.TrdHeader header = 1;</code>
     */
    public Trd_Common.TrdCommon.TrdHeaderOrBuilder getHeaderOrBuilder() {
      return header_ == null ? Trd_Common.TrdCommon.TrdHeader.getDefaultInstance() : header_;
    }

    public static final int ORDER_FIELD_NUMBER = 2;
    private Trd_Common.TrdCommon.Order order_;
    /**
     * <pre>
     *订单结构
     * </pre>
     *
     * <code>required .Trd_Common.Order order = 2;</code>
     */
    public boolean hasOrder() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <pre>
     *订单结构
     * </pre>
     *
     * <code>required .Trd_Common.Order order = 2;</code>
     */
    public Trd_Common.TrdCommon.Order getOrder() {
      return order_ == null ? Trd_Common.TrdCommon.Order.getDefaultInstance() : order_;
    }
    /**
     * <pre>
     *订单结构
     * </pre>
     *
     * <code>required .Trd_Common.Order order = 2;</code>
     */
    public Trd_Common.TrdCommon.OrderOrBuilder getOrderOrBuilder() {
      return order_ == null ? Trd_Common.TrdCommon.Order.getDefaultInstance() : order_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasHeader()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasOrder()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getHeader().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getOrder().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeMessage(1, getHeader());
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeMessage(2, getOrder());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getHeader());
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getOrder());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Trd_UpdateOrder.TrdUpdateOrder.S2C)) {
        return super.equals(obj);
      }
      Trd_UpdateOrder.TrdUpdateOrder.S2C other = (Trd_UpdateOrder.TrdUpdateOrder.S2C) obj;

      if (hasHeader() != other.hasHeader()) return false;
      if (hasHeader()) {
        if (!getHeader()
            .equals(other.getHeader())) return false;
      }
      if (hasOrder() != other.hasOrder()) return false;
      if (hasOrder()) {
        if (!getOrder()
            .equals(other.getOrder())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasHeader()) {
        hash = (37 * hash) + HEADER_FIELD_NUMBER;
        hash = (53 * hash) + getHeader().hashCode();
      }
      if (hasOrder()) {
        hash = (37 * hash) + ORDER_FIELD_NUMBER;
        hash = (53 * hash) + getOrder().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Trd_UpdateOrder.TrdUpdateOrder.S2C parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Trd_UpdateOrder.TrdUpdateOrder.S2C parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Trd_UpdateOrder.TrdUpdateOrder.S2C parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Trd_UpdateOrder.TrdUpdateOrder.S2C parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Trd_UpdateOrder.TrdUpdateOrder.S2C parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Trd_UpdateOrder.TrdUpdateOrder.S2C parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Trd_UpdateOrder.TrdUpdateOrder.S2C parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Trd_UpdateOrder.TrdUpdateOrder.S2C parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Trd_UpdateOrder.TrdUpdateOrder.S2C parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Trd_UpdateOrder.TrdUpdateOrder.S2C parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Trd_UpdateOrder.TrdUpdateOrder.S2C parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Trd_UpdateOrder.TrdUpdateOrder.S2C parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Trd_UpdateOrder.TrdUpdateOrder.S2C prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Trd_UpdateOrder.S2C}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Trd_UpdateOrder.S2C)
        Trd_UpdateOrder.TrdUpdateOrder.S2COrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Trd_UpdateOrder.TrdUpdateOrder.internal_static_Trd_UpdateOrder_S2C_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Trd_UpdateOrder.TrdUpdateOrder.internal_static_Trd_UpdateOrder_S2C_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Trd_UpdateOrder.TrdUpdateOrder.S2C.class, Trd_UpdateOrder.TrdUpdateOrder.S2C.Builder.class);
      }

      // Construct using Trd_UpdateOrder.TrdUpdateOrder.S2C.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getHeaderFieldBuilder();
          getOrderFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (headerBuilder_ == null) {
          header_ = null;
        } else {
          headerBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        if (orderBuilder_ == null) {
          order_ = null;
        } else {
          orderBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Trd_UpdateOrder.TrdUpdateOrder.internal_static_Trd_UpdateOrder_S2C_descriptor;
      }

      @java.lang.Override
      public Trd_UpdateOrder.TrdUpdateOrder.S2C getDefaultInstanceForType() {
        return Trd_UpdateOrder.TrdUpdateOrder.S2C.getDefaultInstance();
      }

      @java.lang.Override
      public Trd_UpdateOrder.TrdUpdateOrder.S2C build() {
        Trd_UpdateOrder.TrdUpdateOrder.S2C result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public Trd_UpdateOrder.TrdUpdateOrder.S2C buildPartial() {
        Trd_UpdateOrder.TrdUpdateOrder.S2C result = new Trd_UpdateOrder.TrdUpdateOrder.S2C(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          if (headerBuilder_ == null) {
            result.header_ = header_;
          } else {
            result.header_ = headerBuilder_.build();
          }
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          if (orderBuilder_ == null) {
            result.order_ = order_;
          } else {
            result.order_ = orderBuilder_.build();
          }
          to_bitField0_ |= 0x00000002;
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Trd_UpdateOrder.TrdUpdateOrder.S2C) {
          return mergeFrom((Trd_UpdateOrder.TrdUpdateOrder.S2C)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Trd_UpdateOrder.TrdUpdateOrder.S2C other) {
        if (other == Trd_UpdateOrder.TrdUpdateOrder.S2C.getDefaultInstance()) return this;
        if (other.hasHeader()) {
          mergeHeader(other.getHeader());
        }
        if (other.hasOrder()) {
          mergeOrder(other.getOrder());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasHeader()) {
          return false;
        }
        if (!hasOrder()) {
          return false;
        }
        if (!getHeader().isInitialized()) {
          return false;
        }
        if (!getOrder().isInitialized()) {
          return false;
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Trd_UpdateOrder.TrdUpdateOrder.S2C parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Trd_UpdateOrder.TrdUpdateOrder.S2C) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private Trd_Common.TrdCommon.TrdHeader header_;
      private com.google.protobuf.SingleFieldBuilderV3<
          Trd_Common.TrdCommon.TrdHeader, Trd_Common.TrdCommon.TrdHeader.Builder, Trd_Common.TrdCommon.TrdHeaderOrBuilder> headerBuilder_;
      /**
       * <pre>
       *交易公共参数头
       * </pre>
       *
       * <code>required .Trd_Common.TrdHeader header = 1;</code>
       */
      public boolean hasHeader() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <pre>
       *交易公共参数头
       * </pre>
       *
       * <code>required .Trd_Common.TrdHeader header = 1;</code>
       */
      public Trd_Common.TrdCommon.TrdHeader getHeader() {
        if (headerBuilder_ == null) {
          return header_ == null ? Trd_Common.TrdCommon.TrdHeader.getDefaultInstance() : header_;
        } else {
          return headerBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       *交易公共参数头
       * </pre>
       *
       * <code>required .Trd_Common.TrdHeader header = 1;</code>
       */
      public Builder setHeader(Trd_Common.TrdCommon.TrdHeader value) {
        if (headerBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          header_ = value;
          onChanged();
        } else {
          headerBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <pre>
       *交易公共参数头
       * </pre>
       *
       * <code>required .Trd_Common.TrdHeader header = 1;</code>
       */
      public Builder setHeader(
          Trd_Common.TrdCommon.TrdHeader.Builder builderForValue) {
        if (headerBuilder_ == null) {
          header_ = builderForValue.build();
          onChanged();
        } else {
          headerBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <pre>
       *交易公共参数头
       * </pre>
       *
       * <code>required .Trd_Common.TrdHeader header = 1;</code>
       */
      public Builder mergeHeader(Trd_Common.TrdCommon.TrdHeader value) {
        if (headerBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0) &&
              header_ != null &&
              header_ != Trd_Common.TrdCommon.TrdHeader.getDefaultInstance()) {
            header_ =
              Trd_Common.TrdCommon.TrdHeader.newBuilder(header_).mergeFrom(value).buildPartial();
          } else {
            header_ = value;
          }
          onChanged();
        } else {
          headerBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <pre>
       *交易公共参数头
       * </pre>
       *
       * <code>required .Trd_Common.TrdHeader header = 1;</code>
       */
      public Builder clearHeader() {
        if (headerBuilder_ == null) {
          header_ = null;
          onChanged();
        } else {
          headerBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      /**
       * <pre>
       *交易公共参数头
       * </pre>
       *
       * <code>required .Trd_Common.TrdHeader header = 1;</code>
       */
      public Trd_Common.TrdCommon.TrdHeader.Builder getHeaderBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getHeaderFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       *交易公共参数头
       * </pre>
       *
       * <code>required .Trd_Common.TrdHeader header = 1;</code>
       */
      public Trd_Common.TrdCommon.TrdHeaderOrBuilder getHeaderOrBuilder() {
        if (headerBuilder_ != null) {
          return headerBuilder_.getMessageOrBuilder();
        } else {
          return header_ == null ?
              Trd_Common.TrdCommon.TrdHeader.getDefaultInstance() : header_;
        }
      }
      /**
       * <pre>
       *交易公共参数头
       * </pre>
       *
       * <code>required .Trd_Common.TrdHeader header = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          Trd_Common.TrdCommon.TrdHeader, Trd_Common.TrdCommon.TrdHeader.Builder, Trd_Common.TrdCommon.TrdHeaderOrBuilder> 
          getHeaderFieldBuilder() {
        if (headerBuilder_ == null) {
          headerBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              Trd_Common.TrdCommon.TrdHeader, Trd_Common.TrdCommon.TrdHeader.Builder, Trd_Common.TrdCommon.TrdHeaderOrBuilder>(
                  getHeader(),
                  getParentForChildren(),
                  isClean());
          header_ = null;
        }
        return headerBuilder_;
      }

      private Trd_Common.TrdCommon.Order order_;
      private com.google.protobuf.SingleFieldBuilderV3<
          Trd_Common.TrdCommon.Order, Trd_Common.TrdCommon.Order.Builder, Trd_Common.TrdCommon.OrderOrBuilder> orderBuilder_;
      /**
       * <pre>
       *订单结构
       * </pre>
       *
       * <code>required .Trd_Common.Order order = 2;</code>
       */
      public boolean hasOrder() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <pre>
       *订单结构
       * </pre>
       *
       * <code>required .Trd_Common.Order order = 2;</code>
       */
      public Trd_Common.TrdCommon.Order getOrder() {
        if (orderBuilder_ == null) {
          return order_ == null ? Trd_Common.TrdCommon.Order.getDefaultInstance() : order_;
        } else {
          return orderBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       *订单结构
       * </pre>
       *
       * <code>required .Trd_Common.Order order = 2;</code>
       */
      public Builder setOrder(Trd_Common.TrdCommon.Order value) {
        if (orderBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          order_ = value;
          onChanged();
        } else {
          orderBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <pre>
       *订单结构
       * </pre>
       *
       * <code>required .Trd_Common.Order order = 2;</code>
       */
      public Builder setOrder(
          Trd_Common.TrdCommon.Order.Builder builderForValue) {
        if (orderBuilder_ == null) {
          order_ = builderForValue.build();
          onChanged();
        } else {
          orderBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <pre>
       *订单结构
       * </pre>
       *
       * <code>required .Trd_Common.Order order = 2;</code>
       */
      public Builder mergeOrder(Trd_Common.TrdCommon.Order value) {
        if (orderBuilder_ == null) {
          if (((bitField0_ & 0x00000002) != 0) &&
              order_ != null &&
              order_ != Trd_Common.TrdCommon.Order.getDefaultInstance()) {
            order_ =
              Trd_Common.TrdCommon.Order.newBuilder(order_).mergeFrom(value).buildPartial();
          } else {
            order_ = value;
          }
          onChanged();
        } else {
          orderBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <pre>
       *订单结构
       * </pre>
       *
       * <code>required .Trd_Common.Order order = 2;</code>
       */
      public Builder clearOrder() {
        if (orderBuilder_ == null) {
          order_ = null;
          onChanged();
        } else {
          orderBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      /**
       * <pre>
       *订单结构
       * </pre>
       *
       * <code>required .Trd_Common.Order order = 2;</code>
       */
      public Trd_Common.TrdCommon.Order.Builder getOrderBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getOrderFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       *订单结构
       * </pre>
       *
       * <code>required .Trd_Common.Order order = 2;</code>
       */
      public Trd_Common.TrdCommon.OrderOrBuilder getOrderOrBuilder() {
        if (orderBuilder_ != null) {
          return orderBuilder_.getMessageOrBuilder();
        } else {
          return order_ == null ?
              Trd_Common.TrdCommon.Order.getDefaultInstance() : order_;
        }
      }
      /**
       * <pre>
       *订单结构
       * </pre>
       *
       * <code>required .Trd_Common.Order order = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          Trd_Common.TrdCommon.Order, Trd_Common.TrdCommon.Order.Builder, Trd_Common.TrdCommon.OrderOrBuilder> 
          getOrderFieldBuilder() {
        if (orderBuilder_ == null) {
          orderBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              Trd_Common.TrdCommon.Order, Trd_Common.TrdCommon.Order.Builder, Trd_Common.TrdCommon.OrderOrBuilder>(
                  getOrder(),
                  getParentForChildren(),
                  isClean());
          order_ = null;
        }
        return orderBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Trd_UpdateOrder.S2C)
    }

    // @@protoc_insertion_point(class_scope:Trd_UpdateOrder.S2C)
    private static final Trd_UpdateOrder.TrdUpdateOrder.S2C DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Trd_UpdateOrder.TrdUpdateOrder.S2C();
    }

    public static Trd_UpdateOrder.TrdUpdateOrder.S2C getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<S2C>
        PARSER = new com.google.protobuf.AbstractParser<S2C>() {
      @java.lang.Override
      public S2C parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new S2C(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<S2C> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<S2C> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public Trd_UpdateOrder.TrdUpdateOrder.S2C getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Trd_UpdateOrder.Response)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *以下3个字段每条协议都有，注释说明在InitConnect.proto中
     * </pre>
     *
     * <code>required int32 retType = 1 [default = -400];</code>
     */
    boolean hasRetType();
    /**
     * <pre>
     *以下3个字段每条协议都有，注释说明在InitConnect.proto中
     * </pre>
     *
     * <code>required int32 retType = 1 [default = -400];</code>
     */
    int getRetType();

    /**
     * <code>optional string retMsg = 2;</code>
     */
    boolean hasRetMsg();
    /**
     * <code>optional string retMsg = 2;</code>
     */
    java.lang.String getRetMsg();
    /**
     * <code>optional string retMsg = 2;</code>
     */
    com.google.protobuf.ByteString
        getRetMsgBytes();

    /**
     * <code>optional int32 errCode = 3;</code>
     */
    boolean hasErrCode();
    /**
     * <code>optional int32 errCode = 3;</code>
     */
    int getErrCode();

    /**
     * <code>optional .Trd_UpdateOrder.S2C s2c = 4;</code>
     */
    boolean hasS2C();
    /**
     * <code>optional .Trd_UpdateOrder.S2C s2c = 4;</code>
     */
    Trd_UpdateOrder.TrdUpdateOrder.S2C getS2C();
    /**
     * <code>optional .Trd_UpdateOrder.S2C s2c = 4;</code>
     */
    Trd_UpdateOrder.TrdUpdateOrder.S2COrBuilder getS2COrBuilder();
  }
  /**
   * Protobuf type {@code Trd_UpdateOrder.Response}
   */
  public  static final class Response extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Trd_UpdateOrder.Response)
      ResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Response.newBuilder() to construct.
    private Response(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Response() {
      retType_ = -400;
      retMsg_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Response(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              bitField0_ |= 0x00000001;
              retType_ = input.readInt32();
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              retMsg_ = bs;
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              errCode_ = input.readInt32();
              break;
            }
            case 34: {
              Trd_UpdateOrder.TrdUpdateOrder.S2C.Builder subBuilder = null;
              if (((bitField0_ & 0x00000008) != 0)) {
                subBuilder = s2C_.toBuilder();
              }
              s2C_ = input.readMessage(Trd_UpdateOrder.TrdUpdateOrder.S2C.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(s2C_);
                s2C_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000008;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Trd_UpdateOrder.TrdUpdateOrder.internal_static_Trd_UpdateOrder_Response_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Trd_UpdateOrder.TrdUpdateOrder.internal_static_Trd_UpdateOrder_Response_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Trd_UpdateOrder.TrdUpdateOrder.Response.class, Trd_UpdateOrder.TrdUpdateOrder.Response.Builder.class);
    }

    private int bitField0_;
    public static final int RETTYPE_FIELD_NUMBER = 1;
    private int retType_;
    /**
     * <pre>
     *以下3个字段每条协议都有，注释说明在InitConnect.proto中
     * </pre>
     *
     * <code>required int32 retType = 1 [default = -400];</code>
     */
    public boolean hasRetType() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     *以下3个字段每条协议都有，注释说明在InitConnect.proto中
     * </pre>
     *
     * <code>required int32 retType = 1 [default = -400];</code>
     */
    public int getRetType() {
      return retType_;
    }

    public static final int RETMSG_FIELD_NUMBER = 2;
    private volatile java.lang.Object retMsg_;
    /**
     * <code>optional string retMsg = 2;</code>
     */
    public boolean hasRetMsg() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional string retMsg = 2;</code>
     */
    public java.lang.String getRetMsg() {
      java.lang.Object ref = retMsg_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          retMsg_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string retMsg = 2;</code>
     */
    public com.google.protobuf.ByteString
        getRetMsgBytes() {
      java.lang.Object ref = retMsg_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        retMsg_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ERRCODE_FIELD_NUMBER = 3;
    private int errCode_;
    /**
     * <code>optional int32 errCode = 3;</code>
     */
    public boolean hasErrCode() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional int32 errCode = 3;</code>
     */
    public int getErrCode() {
      return errCode_;
    }

    public static final int S2C_FIELD_NUMBER = 4;
    private Trd_UpdateOrder.TrdUpdateOrder.S2C s2C_;
    /**
     * <code>optional .Trd_UpdateOrder.S2C s2c = 4;</code>
     */
    public boolean hasS2C() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>optional .Trd_UpdateOrder.S2C s2c = 4;</code>
     */
    public Trd_UpdateOrder.TrdUpdateOrder.S2C getS2C() {
      return s2C_ == null ? Trd_UpdateOrder.TrdUpdateOrder.S2C.getDefaultInstance() : s2C_;
    }
    /**
     * <code>optional .Trd_UpdateOrder.S2C s2c = 4;</code>
     */
    public Trd_UpdateOrder.TrdUpdateOrder.S2COrBuilder getS2COrBuilder() {
      return s2C_ == null ? Trd_UpdateOrder.TrdUpdateOrder.S2C.getDefaultInstance() : s2C_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasRetType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (hasS2C()) {
        if (!getS2C().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeInt32(1, retType_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, retMsg_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        output.writeInt32(3, errCode_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        output.writeMessage(4, getS2C());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, retType_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, retMsg_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, errCode_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, getS2C());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Trd_UpdateOrder.TrdUpdateOrder.Response)) {
        return super.equals(obj);
      }
      Trd_UpdateOrder.TrdUpdateOrder.Response other = (Trd_UpdateOrder.TrdUpdateOrder.Response) obj;

      if (hasRetType() != other.hasRetType()) return false;
      if (hasRetType()) {
        if (getRetType()
            != other.getRetType()) return false;
      }
      if (hasRetMsg() != other.hasRetMsg()) return false;
      if (hasRetMsg()) {
        if (!getRetMsg()
            .equals(other.getRetMsg())) return false;
      }
      if (hasErrCode() != other.hasErrCode()) return false;
      if (hasErrCode()) {
        if (getErrCode()
            != other.getErrCode()) return false;
      }
      if (hasS2C() != other.hasS2C()) return false;
      if (hasS2C()) {
        if (!getS2C()
            .equals(other.getS2C())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasRetType()) {
        hash = (37 * hash) + RETTYPE_FIELD_NUMBER;
        hash = (53 * hash) + getRetType();
      }
      if (hasRetMsg()) {
        hash = (37 * hash) + RETMSG_FIELD_NUMBER;
        hash = (53 * hash) + getRetMsg().hashCode();
      }
      if (hasErrCode()) {
        hash = (37 * hash) + ERRCODE_FIELD_NUMBER;
        hash = (53 * hash) + getErrCode();
      }
      if (hasS2C()) {
        hash = (37 * hash) + S2C_FIELD_NUMBER;
        hash = (53 * hash) + getS2C().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Trd_UpdateOrder.TrdUpdateOrder.Response parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Trd_UpdateOrder.TrdUpdateOrder.Response parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Trd_UpdateOrder.TrdUpdateOrder.Response parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Trd_UpdateOrder.TrdUpdateOrder.Response parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Trd_UpdateOrder.TrdUpdateOrder.Response parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Trd_UpdateOrder.TrdUpdateOrder.Response parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Trd_UpdateOrder.TrdUpdateOrder.Response parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Trd_UpdateOrder.TrdUpdateOrder.Response parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Trd_UpdateOrder.TrdUpdateOrder.Response parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Trd_UpdateOrder.TrdUpdateOrder.Response parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Trd_UpdateOrder.TrdUpdateOrder.Response parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Trd_UpdateOrder.TrdUpdateOrder.Response parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Trd_UpdateOrder.TrdUpdateOrder.Response prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Trd_UpdateOrder.Response}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Trd_UpdateOrder.Response)
        Trd_UpdateOrder.TrdUpdateOrder.ResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Trd_UpdateOrder.TrdUpdateOrder.internal_static_Trd_UpdateOrder_Response_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Trd_UpdateOrder.TrdUpdateOrder.internal_static_Trd_UpdateOrder_Response_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Trd_UpdateOrder.TrdUpdateOrder.Response.class, Trd_UpdateOrder.TrdUpdateOrder.Response.Builder.class);
      }

      // Construct using Trd_UpdateOrder.TrdUpdateOrder.Response.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getS2CFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        retType_ = -400;
        bitField0_ = (bitField0_ & ~0x00000001);
        retMsg_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        errCode_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        if (s2CBuilder_ == null) {
          s2C_ = null;
        } else {
          s2CBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Trd_UpdateOrder.TrdUpdateOrder.internal_static_Trd_UpdateOrder_Response_descriptor;
      }

      @java.lang.Override
      public Trd_UpdateOrder.TrdUpdateOrder.Response getDefaultInstanceForType() {
        return Trd_UpdateOrder.TrdUpdateOrder.Response.getDefaultInstance();
      }

      @java.lang.Override
      public Trd_UpdateOrder.TrdUpdateOrder.Response build() {
        Trd_UpdateOrder.TrdUpdateOrder.Response result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public Trd_UpdateOrder.TrdUpdateOrder.Response buildPartial() {
        Trd_UpdateOrder.TrdUpdateOrder.Response result = new Trd_UpdateOrder.TrdUpdateOrder.Response(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          to_bitField0_ |= 0x00000001;
        }
        result.retType_ = retType_;
        if (((from_bitField0_ & 0x00000002) != 0)) {
          to_bitField0_ |= 0x00000002;
        }
        result.retMsg_ = retMsg_;
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.errCode_ = errCode_;
          to_bitField0_ |= 0x00000004;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          if (s2CBuilder_ == null) {
            result.s2C_ = s2C_;
          } else {
            result.s2C_ = s2CBuilder_.build();
          }
          to_bitField0_ |= 0x00000008;
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Trd_UpdateOrder.TrdUpdateOrder.Response) {
          return mergeFrom((Trd_UpdateOrder.TrdUpdateOrder.Response)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Trd_UpdateOrder.TrdUpdateOrder.Response other) {
        if (other == Trd_UpdateOrder.TrdUpdateOrder.Response.getDefaultInstance()) return this;
        if (other.hasRetType()) {
          setRetType(other.getRetType());
        }
        if (other.hasRetMsg()) {
          bitField0_ |= 0x00000002;
          retMsg_ = other.retMsg_;
          onChanged();
        }
        if (other.hasErrCode()) {
          setErrCode(other.getErrCode());
        }
        if (other.hasS2C()) {
          mergeS2C(other.getS2C());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasRetType()) {
          return false;
        }
        if (hasS2C()) {
          if (!getS2C().isInitialized()) {
            return false;
          }
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Trd_UpdateOrder.TrdUpdateOrder.Response parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Trd_UpdateOrder.TrdUpdateOrder.Response) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int retType_ = -400;
      /**
       * <pre>
       *以下3个字段每条协议都有，注释说明在InitConnect.proto中
       * </pre>
       *
       * <code>required int32 retType = 1 [default = -400];</code>
       */
      public boolean hasRetType() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <pre>
       *以下3个字段每条协议都有，注释说明在InitConnect.proto中
       * </pre>
       *
       * <code>required int32 retType = 1 [default = -400];</code>
       */
      public int getRetType() {
        return retType_;
      }
      /**
       * <pre>
       *以下3个字段每条协议都有，注释说明在InitConnect.proto中
       * </pre>
       *
       * <code>required int32 retType = 1 [default = -400];</code>
       */
      public Builder setRetType(int value) {
        bitField0_ |= 0x00000001;
        retType_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *以下3个字段每条协议都有，注释说明在InitConnect.proto中
       * </pre>
       *
       * <code>required int32 retType = 1 [default = -400];</code>
       */
      public Builder clearRetType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        retType_ = -400;
        onChanged();
        return this;
      }

      private java.lang.Object retMsg_ = "";
      /**
       * <code>optional string retMsg = 2;</code>
       */
      public boolean hasRetMsg() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>optional string retMsg = 2;</code>
       */
      public java.lang.String getRetMsg() {
        java.lang.Object ref = retMsg_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            retMsg_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string retMsg = 2;</code>
       */
      public com.google.protobuf.ByteString
          getRetMsgBytes() {
        java.lang.Object ref = retMsg_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          retMsg_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string retMsg = 2;</code>
       */
      public Builder setRetMsg(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        retMsg_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string retMsg = 2;</code>
       */
      public Builder clearRetMsg() {
        bitField0_ = (bitField0_ & ~0x00000002);
        retMsg_ = getDefaultInstance().getRetMsg();
        onChanged();
        return this;
      }
      /**
       * <code>optional string retMsg = 2;</code>
       */
      public Builder setRetMsgBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        retMsg_ = value;
        onChanged();
        return this;
      }

      private int errCode_ ;
      /**
       * <code>optional int32 errCode = 3;</code>
       */
      public boolean hasErrCode() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>optional int32 errCode = 3;</code>
       */
      public int getErrCode() {
        return errCode_;
      }
      /**
       * <code>optional int32 errCode = 3;</code>
       */
      public Builder setErrCode(int value) {
        bitField0_ |= 0x00000004;
        errCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 errCode = 3;</code>
       */
      public Builder clearErrCode() {
        bitField0_ = (bitField0_ & ~0x00000004);
        errCode_ = 0;
        onChanged();
        return this;
      }

      private Trd_UpdateOrder.TrdUpdateOrder.S2C s2C_;
      private com.google.protobuf.SingleFieldBuilderV3<
          Trd_UpdateOrder.TrdUpdateOrder.S2C, Trd_UpdateOrder.TrdUpdateOrder.S2C.Builder, Trd_UpdateOrder.TrdUpdateOrder.S2COrBuilder> s2CBuilder_;
      /**
       * <code>optional .Trd_UpdateOrder.S2C s2c = 4;</code>
       */
      public boolean hasS2C() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <code>optional .Trd_UpdateOrder.S2C s2c = 4;</code>
       */
      public Trd_UpdateOrder.TrdUpdateOrder.S2C getS2C() {
        if (s2CBuilder_ == null) {
          return s2C_ == null ? Trd_UpdateOrder.TrdUpdateOrder.S2C.getDefaultInstance() : s2C_;
        } else {
          return s2CBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .Trd_UpdateOrder.S2C s2c = 4;</code>
       */
      public Builder setS2C(Trd_UpdateOrder.TrdUpdateOrder.S2C value) {
        if (s2CBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          s2C_ = value;
          onChanged();
        } else {
          s2CBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <code>optional .Trd_UpdateOrder.S2C s2c = 4;</code>
       */
      public Builder setS2C(
          Trd_UpdateOrder.TrdUpdateOrder.S2C.Builder builderForValue) {
        if (s2CBuilder_ == null) {
          s2C_ = builderForValue.build();
          onChanged();
        } else {
          s2CBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <code>optional .Trd_UpdateOrder.S2C s2c = 4;</code>
       */
      public Builder mergeS2C(Trd_UpdateOrder.TrdUpdateOrder.S2C value) {
        if (s2CBuilder_ == null) {
          if (((bitField0_ & 0x00000008) != 0) &&
              s2C_ != null &&
              s2C_ != Trd_UpdateOrder.TrdUpdateOrder.S2C.getDefaultInstance()) {
            s2C_ =
              Trd_UpdateOrder.TrdUpdateOrder.S2C.newBuilder(s2C_).mergeFrom(value).buildPartial();
          } else {
            s2C_ = value;
          }
          onChanged();
        } else {
          s2CBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <code>optional .Trd_UpdateOrder.S2C s2c = 4;</code>
       */
      public Builder clearS2C() {
        if (s2CBuilder_ == null) {
          s2C_ = null;
          onChanged();
        } else {
          s2CBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }
      /**
       * <code>optional .Trd_UpdateOrder.S2C s2c = 4;</code>
       */
      public Trd_UpdateOrder.TrdUpdateOrder.S2C.Builder getS2CBuilder() {
        bitField0_ |= 0x00000008;
        onChanged();
        return getS2CFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .Trd_UpdateOrder.S2C s2c = 4;</code>
       */
      public Trd_UpdateOrder.TrdUpdateOrder.S2COrBuilder getS2COrBuilder() {
        if (s2CBuilder_ != null) {
          return s2CBuilder_.getMessageOrBuilder();
        } else {
          return s2C_ == null ?
              Trd_UpdateOrder.TrdUpdateOrder.S2C.getDefaultInstance() : s2C_;
        }
      }
      /**
       * <code>optional .Trd_UpdateOrder.S2C s2c = 4;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          Trd_UpdateOrder.TrdUpdateOrder.S2C, Trd_UpdateOrder.TrdUpdateOrder.S2C.Builder, Trd_UpdateOrder.TrdUpdateOrder.S2COrBuilder> 
          getS2CFieldBuilder() {
        if (s2CBuilder_ == null) {
          s2CBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              Trd_UpdateOrder.TrdUpdateOrder.S2C, Trd_UpdateOrder.TrdUpdateOrder.S2C.Builder, Trd_UpdateOrder.TrdUpdateOrder.S2COrBuilder>(
                  getS2C(),
                  getParentForChildren(),
                  isClean());
          s2C_ = null;
        }
        return s2CBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Trd_UpdateOrder.Response)
    }

    // @@protoc_insertion_point(class_scope:Trd_UpdateOrder.Response)
    private static final Trd_UpdateOrder.TrdUpdateOrder.Response DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Trd_UpdateOrder.TrdUpdateOrder.Response();
    }

    public static Trd_UpdateOrder.TrdUpdateOrder.Response getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Response>
        PARSER = new com.google.protobuf.AbstractParser<Response>() {
      @java.lang.Override
      public Response parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Response(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Response> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Response> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public Trd_UpdateOrder.TrdUpdateOrder.Response getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Trd_UpdateOrder_S2C_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Trd_UpdateOrder_S2C_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Trd_UpdateOrder_Response_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Trd_UpdateOrder_Response_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025Trd_UpdateOrder.proto\022\017Trd_UpdateOrder" +
      "\032\014Common.proto\032\020Trd_Common.proto\"N\n\003S2C\022" +
      "%\n\006header\030\001 \002(\0132\025.Trd_Common.TrdHeader\022 " +
      "\n\005order\030\002 \002(\0132\021.Trd_Common.Order\"e\n\010Resp" +
      "onse\022\025\n\007retType\030\001 \002(\005:\004-400\022\016\n\006retMsg\030\002 " +
      "\001(\t\022\017\n\007errCode\030\003 \001(\005\022!\n\003s2c\030\004 \001(\0132\024.Trd_" +
      "UpdateOrder.S2C"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          Common.Common.getDescriptor(),
          Trd_Common.TrdCommon.getDescriptor(),
        }, assigner);
    internal_static_Trd_UpdateOrder_S2C_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Trd_UpdateOrder_S2C_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Trd_UpdateOrder_S2C_descriptor,
        new java.lang.String[] { "Header", "Order", });
    internal_static_Trd_UpdateOrder_Response_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Trd_UpdateOrder_Response_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Trd_UpdateOrder_Response_descriptor,
        new java.lang.String[] { "RetType", "RetMsg", "ErrCode", "S2C", });
    Common.Common.getDescriptor();
    Trd_Common.TrdCommon.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
