// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Qot_UpdateKL.proto

package Qot_UpdateKL;

public final class QotUpdateKL {
  private QotUpdateKL() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface S2COrBuilder extends
      // @@protoc_insertion_point(interface_extends:Qot_UpdateKL.S2C)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *Qot_Common.RehabType,复权类型
     * </pre>
     *
     * <code>required int32 rehabType = 1;</code>
     */
    boolean hasRehabType();
    /**
     * <pre>
     *Qot_Common.RehabType,复权类型
     * </pre>
     *
     * <code>required int32 rehabType = 1;</code>
     */
    int getRehabType();

    /**
     * <pre>
     *Qot_Common.KLType,K线类型
     * </pre>
     *
     * <code>required int32 klType = 2;</code>
     */
    boolean hasKlType();
    /**
     * <pre>
     *Qot_Common.KLType,K线类型
     * </pre>
     *
     * <code>required int32 klType = 2;</code>
     */
    int getKlType();

    /**
     * <pre>
     *股票
     * </pre>
     *
     * <code>required .Qot_Common.Security security = 3;</code>
     */
    boolean hasSecurity();
    /**
     * <pre>
     *股票
     * </pre>
     *
     * <code>required .Qot_Common.Security security = 3;</code>
     */
    Qot_Common.QotCommon.Security getSecurity();
    /**
     * <pre>
     *股票
     * </pre>
     *
     * <code>required .Qot_Common.Security security = 3;</code>
     */
    Qot_Common.QotCommon.SecurityOrBuilder getSecurityOrBuilder();

    /**
     * <pre>
     *推送的k线点
     * </pre>
     *
     * <code>repeated .Qot_Common.KLine klList = 4;</code>
     */
    java.util.List<Qot_Common.QotCommon.KLine> 
        getKlListList();
    /**
     * <pre>
     *推送的k线点
     * </pre>
     *
     * <code>repeated .Qot_Common.KLine klList = 4;</code>
     */
    Qot_Common.QotCommon.KLine getKlList(int index);
    /**
     * <pre>
     *推送的k线点
     * </pre>
     *
     * <code>repeated .Qot_Common.KLine klList = 4;</code>
     */
    int getKlListCount();
    /**
     * <pre>
     *推送的k线点
     * </pre>
     *
     * <code>repeated .Qot_Common.KLine klList = 4;</code>
     */
    java.util.List<? extends Qot_Common.QotCommon.KLineOrBuilder> 
        getKlListOrBuilderList();
    /**
     * <pre>
     *推送的k线点
     * </pre>
     *
     * <code>repeated .Qot_Common.KLine klList = 4;</code>
     */
    Qot_Common.QotCommon.KLineOrBuilder getKlListOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code Qot_UpdateKL.S2C}
   */
  public  static final class S2C extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Qot_UpdateKL.S2C)
      S2COrBuilder {
  private static final long serialVersionUID = 0L;
    // Use S2C.newBuilder() to construct.
    private S2C(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private S2C() {
      klList_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private S2C(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              bitField0_ |= 0x00000001;
              rehabType_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              klType_ = input.readInt32();
              break;
            }
            case 26: {
              Qot_Common.QotCommon.Security.Builder subBuilder = null;
              if (((bitField0_ & 0x00000004) != 0)) {
                subBuilder = security_.toBuilder();
              }
              security_ = input.readMessage(Qot_Common.QotCommon.Security.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(security_);
                security_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000004;
              break;
            }
            case 34: {
              if (!((mutable_bitField0_ & 0x00000008) != 0)) {
                klList_ = new java.util.ArrayList<Qot_Common.QotCommon.KLine>();
                mutable_bitField0_ |= 0x00000008;
              }
              klList_.add(
                  input.readMessage(Qot_Common.QotCommon.KLine.PARSER, extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000008) != 0)) {
          klList_ = java.util.Collections.unmodifiableList(klList_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Qot_UpdateKL.QotUpdateKL.internal_static_Qot_UpdateKL_S2C_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Qot_UpdateKL.QotUpdateKL.internal_static_Qot_UpdateKL_S2C_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Qot_UpdateKL.QotUpdateKL.S2C.class, Qot_UpdateKL.QotUpdateKL.S2C.Builder.class);
    }

    private int bitField0_;
    public static final int REHABTYPE_FIELD_NUMBER = 1;
    private int rehabType_;
    /**
     * <pre>
     *Qot_Common.RehabType,复权类型
     * </pre>
     *
     * <code>required int32 rehabType = 1;</code>
     */
    public boolean hasRehabType() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     *Qot_Common.RehabType,复权类型
     * </pre>
     *
     * <code>required int32 rehabType = 1;</code>
     */
    public int getRehabType() {
      return rehabType_;
    }

    public static final int KLTYPE_FIELD_NUMBER = 2;
    private int klType_;
    /**
     * <pre>
     *Qot_Common.KLType,K线类型
     * </pre>
     *
     * <code>required int32 klType = 2;</code>
     */
    public boolean hasKlType() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <pre>
     *Qot_Common.KLType,K线类型
     * </pre>
     *
     * <code>required int32 klType = 2;</code>
     */
    public int getKlType() {
      return klType_;
    }

    public static final int SECURITY_FIELD_NUMBER = 3;
    private Qot_Common.QotCommon.Security security_;
    /**
     * <pre>
     *股票
     * </pre>
     *
     * <code>required .Qot_Common.Security security = 3;</code>
     */
    public boolean hasSecurity() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <pre>
     *股票
     * </pre>
     *
     * <code>required .Qot_Common.Security security = 3;</code>
     */
    public Qot_Common.QotCommon.Security getSecurity() {
      return security_ == null ? Qot_Common.QotCommon.Security.getDefaultInstance() : security_;
    }
    /**
     * <pre>
     *股票
     * </pre>
     *
     * <code>required .Qot_Common.Security security = 3;</code>
     */
    public Qot_Common.QotCommon.SecurityOrBuilder getSecurityOrBuilder() {
      return security_ == null ? Qot_Common.QotCommon.Security.getDefaultInstance() : security_;
    }

    public static final int KLLIST_FIELD_NUMBER = 4;
    private java.util.List<Qot_Common.QotCommon.KLine> klList_;
    /**
     * <pre>
     *推送的k线点
     * </pre>
     *
     * <code>repeated .Qot_Common.KLine klList = 4;</code>
     */
    public java.util.List<Qot_Common.QotCommon.KLine> getKlListList() {
      return klList_;
    }
    /**
     * <pre>
     *推送的k线点
     * </pre>
     *
     * <code>repeated .Qot_Common.KLine klList = 4;</code>
     */
    public java.util.List<? extends Qot_Common.QotCommon.KLineOrBuilder> 
        getKlListOrBuilderList() {
      return klList_;
    }
    /**
     * <pre>
     *推送的k线点
     * </pre>
     *
     * <code>repeated .Qot_Common.KLine klList = 4;</code>
     */
    public int getKlListCount() {
      return klList_.size();
    }
    /**
     * <pre>
     *推送的k线点
     * </pre>
     *
     * <code>repeated .Qot_Common.KLine klList = 4;</code>
     */
    public Qot_Common.QotCommon.KLine getKlList(int index) {
      return klList_.get(index);
    }
    /**
     * <pre>
     *推送的k线点
     * </pre>
     *
     * <code>repeated .Qot_Common.KLine klList = 4;</code>
     */
    public Qot_Common.QotCommon.KLineOrBuilder getKlListOrBuilder(
        int index) {
      return klList_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasRehabType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasKlType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSecurity()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getSecurity().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getKlListCount(); i++) {
        if (!getKlList(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeInt32(1, rehabType_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeInt32(2, klType_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        output.writeMessage(3, getSecurity());
      }
      for (int i = 0; i < klList_.size(); i++) {
        output.writeMessage(4, klList_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, rehabType_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, klType_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getSecurity());
      }
      for (int i = 0; i < klList_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, klList_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Qot_UpdateKL.QotUpdateKL.S2C)) {
        return super.equals(obj);
      }
      Qot_UpdateKL.QotUpdateKL.S2C other = (Qot_UpdateKL.QotUpdateKL.S2C) obj;

      if (hasRehabType() != other.hasRehabType()) return false;
      if (hasRehabType()) {
        if (getRehabType()
            != other.getRehabType()) return false;
      }
      if (hasKlType() != other.hasKlType()) return false;
      if (hasKlType()) {
        if (getKlType()
            != other.getKlType()) return false;
      }
      if (hasSecurity() != other.hasSecurity()) return false;
      if (hasSecurity()) {
        if (!getSecurity()
            .equals(other.getSecurity())) return false;
      }
      if (!getKlListList()
          .equals(other.getKlListList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasRehabType()) {
        hash = (37 * hash) + REHABTYPE_FIELD_NUMBER;
        hash = (53 * hash) + getRehabType();
      }
      if (hasKlType()) {
        hash = (37 * hash) + KLTYPE_FIELD_NUMBER;
        hash = (53 * hash) + getKlType();
      }
      if (hasSecurity()) {
        hash = (37 * hash) + SECURITY_FIELD_NUMBER;
        hash = (53 * hash) + getSecurity().hashCode();
      }
      if (getKlListCount() > 0) {
        hash = (37 * hash) + KLLIST_FIELD_NUMBER;
        hash = (53 * hash) + getKlListList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Qot_UpdateKL.QotUpdateKL.S2C parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Qot_UpdateKL.QotUpdateKL.S2C parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Qot_UpdateKL.QotUpdateKL.S2C parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Qot_UpdateKL.QotUpdateKL.S2C parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Qot_UpdateKL.QotUpdateKL.S2C parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Qot_UpdateKL.QotUpdateKL.S2C parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Qot_UpdateKL.QotUpdateKL.S2C parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Qot_UpdateKL.QotUpdateKL.S2C parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Qot_UpdateKL.QotUpdateKL.S2C parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Qot_UpdateKL.QotUpdateKL.S2C parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Qot_UpdateKL.QotUpdateKL.S2C parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Qot_UpdateKL.QotUpdateKL.S2C parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Qot_UpdateKL.QotUpdateKL.S2C prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Qot_UpdateKL.S2C}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Qot_UpdateKL.S2C)
        Qot_UpdateKL.QotUpdateKL.S2COrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Qot_UpdateKL.QotUpdateKL.internal_static_Qot_UpdateKL_S2C_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Qot_UpdateKL.QotUpdateKL.internal_static_Qot_UpdateKL_S2C_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Qot_UpdateKL.QotUpdateKL.S2C.class, Qot_UpdateKL.QotUpdateKL.S2C.Builder.class);
      }

      // Construct using Qot_UpdateKL.QotUpdateKL.S2C.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getSecurityFieldBuilder();
          getKlListFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        rehabType_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        klType_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        if (securityBuilder_ == null) {
          security_ = null;
        } else {
          securityBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        if (klListBuilder_ == null) {
          klList_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
        } else {
          klListBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Qot_UpdateKL.QotUpdateKL.internal_static_Qot_UpdateKL_S2C_descriptor;
      }

      @java.lang.Override
      public Qot_UpdateKL.QotUpdateKL.S2C getDefaultInstanceForType() {
        return Qot_UpdateKL.QotUpdateKL.S2C.getDefaultInstance();
      }

      @java.lang.Override
      public Qot_UpdateKL.QotUpdateKL.S2C build() {
        Qot_UpdateKL.QotUpdateKL.S2C result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public Qot_UpdateKL.QotUpdateKL.S2C buildPartial() {
        Qot_UpdateKL.QotUpdateKL.S2C result = new Qot_UpdateKL.QotUpdateKL.S2C(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.rehabType_ = rehabType_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.klType_ = klType_;
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          if (securityBuilder_ == null) {
            result.security_ = security_;
          } else {
            result.security_ = securityBuilder_.build();
          }
          to_bitField0_ |= 0x00000004;
        }
        if (klListBuilder_ == null) {
          if (((bitField0_ & 0x00000008) != 0)) {
            klList_ = java.util.Collections.unmodifiableList(klList_);
            bitField0_ = (bitField0_ & ~0x00000008);
          }
          result.klList_ = klList_;
        } else {
          result.klList_ = klListBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Qot_UpdateKL.QotUpdateKL.S2C) {
          return mergeFrom((Qot_UpdateKL.QotUpdateKL.S2C)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Qot_UpdateKL.QotUpdateKL.S2C other) {
        if (other == Qot_UpdateKL.QotUpdateKL.S2C.getDefaultInstance()) return this;
        if (other.hasRehabType()) {
          setRehabType(other.getRehabType());
        }
        if (other.hasKlType()) {
          setKlType(other.getKlType());
        }
        if (other.hasSecurity()) {
          mergeSecurity(other.getSecurity());
        }
        if (klListBuilder_ == null) {
          if (!other.klList_.isEmpty()) {
            if (klList_.isEmpty()) {
              klList_ = other.klList_;
              bitField0_ = (bitField0_ & ~0x00000008);
            } else {
              ensureKlListIsMutable();
              klList_.addAll(other.klList_);
            }
            onChanged();
          }
        } else {
          if (!other.klList_.isEmpty()) {
            if (klListBuilder_.isEmpty()) {
              klListBuilder_.dispose();
              klListBuilder_ = null;
              klList_ = other.klList_;
              bitField0_ = (bitField0_ & ~0x00000008);
              klListBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getKlListFieldBuilder() : null;
            } else {
              klListBuilder_.addAllMessages(other.klList_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasRehabType()) {
          return false;
        }
        if (!hasKlType()) {
          return false;
        }
        if (!hasSecurity()) {
          return false;
        }
        if (!getSecurity().isInitialized()) {
          return false;
        }
        for (int i = 0; i < getKlListCount(); i++) {
          if (!getKlList(i).isInitialized()) {
            return false;
          }
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Qot_UpdateKL.QotUpdateKL.S2C parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Qot_UpdateKL.QotUpdateKL.S2C) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int rehabType_ ;
      /**
       * <pre>
       *Qot_Common.RehabType,复权类型
       * </pre>
       *
       * <code>required int32 rehabType = 1;</code>
       */
      public boolean hasRehabType() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <pre>
       *Qot_Common.RehabType,复权类型
       * </pre>
       *
       * <code>required int32 rehabType = 1;</code>
       */
      public int getRehabType() {
        return rehabType_;
      }
      /**
       * <pre>
       *Qot_Common.RehabType,复权类型
       * </pre>
       *
       * <code>required int32 rehabType = 1;</code>
       */
      public Builder setRehabType(int value) {
        bitField0_ |= 0x00000001;
        rehabType_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *Qot_Common.RehabType,复权类型
       * </pre>
       *
       * <code>required int32 rehabType = 1;</code>
       */
      public Builder clearRehabType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        rehabType_ = 0;
        onChanged();
        return this;
      }

      private int klType_ ;
      /**
       * <pre>
       *Qot_Common.KLType,K线类型
       * </pre>
       *
       * <code>required int32 klType = 2;</code>
       */
      public boolean hasKlType() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <pre>
       *Qot_Common.KLType,K线类型
       * </pre>
       *
       * <code>required int32 klType = 2;</code>
       */
      public int getKlType() {
        return klType_;
      }
      /**
       * <pre>
       *Qot_Common.KLType,K线类型
       * </pre>
       *
       * <code>required int32 klType = 2;</code>
       */
      public Builder setKlType(int value) {
        bitField0_ |= 0x00000002;
        klType_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *Qot_Common.KLType,K线类型
       * </pre>
       *
       * <code>required int32 klType = 2;</code>
       */
      public Builder clearKlType() {
        bitField0_ = (bitField0_ & ~0x00000002);
        klType_ = 0;
        onChanged();
        return this;
      }

      private Qot_Common.QotCommon.Security security_;
      private com.google.protobuf.SingleFieldBuilderV3<
          Qot_Common.QotCommon.Security, Qot_Common.QotCommon.Security.Builder, Qot_Common.QotCommon.SecurityOrBuilder> securityBuilder_;
      /**
       * <pre>
       *股票
       * </pre>
       *
       * <code>required .Qot_Common.Security security = 3;</code>
       */
      public boolean hasSecurity() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <pre>
       *股票
       * </pre>
       *
       * <code>required .Qot_Common.Security security = 3;</code>
       */
      public Qot_Common.QotCommon.Security getSecurity() {
        if (securityBuilder_ == null) {
          return security_ == null ? Qot_Common.QotCommon.Security.getDefaultInstance() : security_;
        } else {
          return securityBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       *股票
       * </pre>
       *
       * <code>required .Qot_Common.Security security = 3;</code>
       */
      public Builder setSecurity(Qot_Common.QotCommon.Security value) {
        if (securityBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          security_ = value;
          onChanged();
        } else {
          securityBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <pre>
       *股票
       * </pre>
       *
       * <code>required .Qot_Common.Security security = 3;</code>
       */
      public Builder setSecurity(
          Qot_Common.QotCommon.Security.Builder builderForValue) {
        if (securityBuilder_ == null) {
          security_ = builderForValue.build();
          onChanged();
        } else {
          securityBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <pre>
       *股票
       * </pre>
       *
       * <code>required .Qot_Common.Security security = 3;</code>
       */
      public Builder mergeSecurity(Qot_Common.QotCommon.Security value) {
        if (securityBuilder_ == null) {
          if (((bitField0_ & 0x00000004) != 0) &&
              security_ != null &&
              security_ != Qot_Common.QotCommon.Security.getDefaultInstance()) {
            security_ =
              Qot_Common.QotCommon.Security.newBuilder(security_).mergeFrom(value).buildPartial();
          } else {
            security_ = value;
          }
          onChanged();
        } else {
          securityBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <pre>
       *股票
       * </pre>
       *
       * <code>required .Qot_Common.Security security = 3;</code>
       */
      public Builder clearSecurity() {
        if (securityBuilder_ == null) {
          security_ = null;
          onChanged();
        } else {
          securityBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      /**
       * <pre>
       *股票
       * </pre>
       *
       * <code>required .Qot_Common.Security security = 3;</code>
       */
      public Qot_Common.QotCommon.Security.Builder getSecurityBuilder() {
        bitField0_ |= 0x00000004;
        onChanged();
        return getSecurityFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       *股票
       * </pre>
       *
       * <code>required .Qot_Common.Security security = 3;</code>
       */
      public Qot_Common.QotCommon.SecurityOrBuilder getSecurityOrBuilder() {
        if (securityBuilder_ != null) {
          return securityBuilder_.getMessageOrBuilder();
        } else {
          return security_ == null ?
              Qot_Common.QotCommon.Security.getDefaultInstance() : security_;
        }
      }
      /**
       * <pre>
       *股票
       * </pre>
       *
       * <code>required .Qot_Common.Security security = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          Qot_Common.QotCommon.Security, Qot_Common.QotCommon.Security.Builder, Qot_Common.QotCommon.SecurityOrBuilder> 
          getSecurityFieldBuilder() {
        if (securityBuilder_ == null) {
          securityBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              Qot_Common.QotCommon.Security, Qot_Common.QotCommon.Security.Builder, Qot_Common.QotCommon.SecurityOrBuilder>(
                  getSecurity(),
                  getParentForChildren(),
                  isClean());
          security_ = null;
        }
        return securityBuilder_;
      }

      private java.util.List<Qot_Common.QotCommon.KLine> klList_ =
        java.util.Collections.emptyList();
      private void ensureKlListIsMutable() {
        if (!((bitField0_ & 0x00000008) != 0)) {
          klList_ = new java.util.ArrayList<Qot_Common.QotCommon.KLine>(klList_);
          bitField0_ |= 0x00000008;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          Qot_Common.QotCommon.KLine, Qot_Common.QotCommon.KLine.Builder, Qot_Common.QotCommon.KLineOrBuilder> klListBuilder_;

      /**
       * <pre>
       *推送的k线点
       * </pre>
       *
       * <code>repeated .Qot_Common.KLine klList = 4;</code>
       */
      public java.util.List<Qot_Common.QotCommon.KLine> getKlListList() {
        if (klListBuilder_ == null) {
          return java.util.Collections.unmodifiableList(klList_);
        } else {
          return klListBuilder_.getMessageList();
        }
      }
      /**
       * <pre>
       *推送的k线点
       * </pre>
       *
       * <code>repeated .Qot_Common.KLine klList = 4;</code>
       */
      public int getKlListCount() {
        if (klListBuilder_ == null) {
          return klList_.size();
        } else {
          return klListBuilder_.getCount();
        }
      }
      /**
       * <pre>
       *推送的k线点
       * </pre>
       *
       * <code>repeated .Qot_Common.KLine klList = 4;</code>
       */
      public Qot_Common.QotCommon.KLine getKlList(int index) {
        if (klListBuilder_ == null) {
          return klList_.get(index);
        } else {
          return klListBuilder_.getMessage(index);
        }
      }
      /**
       * <pre>
       *推送的k线点
       * </pre>
       *
       * <code>repeated .Qot_Common.KLine klList = 4;</code>
       */
      public Builder setKlList(
          int index, Qot_Common.QotCommon.KLine value) {
        if (klListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureKlListIsMutable();
          klList_.set(index, value);
          onChanged();
        } else {
          klListBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       *推送的k线点
       * </pre>
       *
       * <code>repeated .Qot_Common.KLine klList = 4;</code>
       */
      public Builder setKlList(
          int index, Qot_Common.QotCommon.KLine.Builder builderForValue) {
        if (klListBuilder_ == null) {
          ensureKlListIsMutable();
          klList_.set(index, builderForValue.build());
          onChanged();
        } else {
          klListBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       *推送的k线点
       * </pre>
       *
       * <code>repeated .Qot_Common.KLine klList = 4;</code>
       */
      public Builder addKlList(Qot_Common.QotCommon.KLine value) {
        if (klListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureKlListIsMutable();
          klList_.add(value);
          onChanged();
        } else {
          klListBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <pre>
       *推送的k线点
       * </pre>
       *
       * <code>repeated .Qot_Common.KLine klList = 4;</code>
       */
      public Builder addKlList(
          int index, Qot_Common.QotCommon.KLine value) {
        if (klListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureKlListIsMutable();
          klList_.add(index, value);
          onChanged();
        } else {
          klListBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       *推送的k线点
       * </pre>
       *
       * <code>repeated .Qot_Common.KLine klList = 4;</code>
       */
      public Builder addKlList(
          Qot_Common.QotCommon.KLine.Builder builderForValue) {
        if (klListBuilder_ == null) {
          ensureKlListIsMutable();
          klList_.add(builderForValue.build());
          onChanged();
        } else {
          klListBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       *推送的k线点
       * </pre>
       *
       * <code>repeated .Qot_Common.KLine klList = 4;</code>
       */
      public Builder addKlList(
          int index, Qot_Common.QotCommon.KLine.Builder builderForValue) {
        if (klListBuilder_ == null) {
          ensureKlListIsMutable();
          klList_.add(index, builderForValue.build());
          onChanged();
        } else {
          klListBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       *推送的k线点
       * </pre>
       *
       * <code>repeated .Qot_Common.KLine klList = 4;</code>
       */
      public Builder addAllKlList(
          java.lang.Iterable<? extends Qot_Common.QotCommon.KLine> values) {
        if (klListBuilder_ == null) {
          ensureKlListIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, klList_);
          onChanged();
        } else {
          klListBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <pre>
       *推送的k线点
       * </pre>
       *
       * <code>repeated .Qot_Common.KLine klList = 4;</code>
       */
      public Builder clearKlList() {
        if (klListBuilder_ == null) {
          klList_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
          onChanged();
        } else {
          klListBuilder_.clear();
        }
        return this;
      }
      /**
       * <pre>
       *推送的k线点
       * </pre>
       *
       * <code>repeated .Qot_Common.KLine klList = 4;</code>
       */
      public Builder removeKlList(int index) {
        if (klListBuilder_ == null) {
          ensureKlListIsMutable();
          klList_.remove(index);
          onChanged();
        } else {
          klListBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <pre>
       *推送的k线点
       * </pre>
       *
       * <code>repeated .Qot_Common.KLine klList = 4;</code>
       */
      public Qot_Common.QotCommon.KLine.Builder getKlListBuilder(
          int index) {
        return getKlListFieldBuilder().getBuilder(index);
      }
      /**
       * <pre>
       *推送的k线点
       * </pre>
       *
       * <code>repeated .Qot_Common.KLine klList = 4;</code>
       */
      public Qot_Common.QotCommon.KLineOrBuilder getKlListOrBuilder(
          int index) {
        if (klListBuilder_ == null) {
          return klList_.get(index);  } else {
          return klListBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <pre>
       *推送的k线点
       * </pre>
       *
       * <code>repeated .Qot_Common.KLine klList = 4;</code>
       */
      public java.util.List<? extends Qot_Common.QotCommon.KLineOrBuilder> 
           getKlListOrBuilderList() {
        if (klListBuilder_ != null) {
          return klListBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(klList_);
        }
      }
      /**
       * <pre>
       *推送的k线点
       * </pre>
       *
       * <code>repeated .Qot_Common.KLine klList = 4;</code>
       */
      public Qot_Common.QotCommon.KLine.Builder addKlListBuilder() {
        return getKlListFieldBuilder().addBuilder(
            Qot_Common.QotCommon.KLine.getDefaultInstance());
      }
      /**
       * <pre>
       *推送的k线点
       * </pre>
       *
       * <code>repeated .Qot_Common.KLine klList = 4;</code>
       */
      public Qot_Common.QotCommon.KLine.Builder addKlListBuilder(
          int index) {
        return getKlListFieldBuilder().addBuilder(
            index, Qot_Common.QotCommon.KLine.getDefaultInstance());
      }
      /**
       * <pre>
       *推送的k线点
       * </pre>
       *
       * <code>repeated .Qot_Common.KLine klList = 4;</code>
       */
      public java.util.List<Qot_Common.QotCommon.KLine.Builder> 
           getKlListBuilderList() {
        return getKlListFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          Qot_Common.QotCommon.KLine, Qot_Common.QotCommon.KLine.Builder, Qot_Common.QotCommon.KLineOrBuilder> 
          getKlListFieldBuilder() {
        if (klListBuilder_ == null) {
          klListBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              Qot_Common.QotCommon.KLine, Qot_Common.QotCommon.KLine.Builder, Qot_Common.QotCommon.KLineOrBuilder>(
                  klList_,
                  ((bitField0_ & 0x00000008) != 0),
                  getParentForChildren(),
                  isClean());
          klList_ = null;
        }
        return klListBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Qot_UpdateKL.S2C)
    }

    // @@protoc_insertion_point(class_scope:Qot_UpdateKL.S2C)
    private static final Qot_UpdateKL.QotUpdateKL.S2C DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Qot_UpdateKL.QotUpdateKL.S2C();
    }

    public static Qot_UpdateKL.QotUpdateKL.S2C getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<S2C>
        PARSER = new com.google.protobuf.AbstractParser<S2C>() {
      @java.lang.Override
      public S2C parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new S2C(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<S2C> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<S2C> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public Qot_UpdateKL.QotUpdateKL.S2C getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Qot_UpdateKL.Response)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *RetType,返回结果
     * </pre>
     *
     * <code>required int32 retType = 1 [default = -400];</code>
     */
    boolean hasRetType();
    /**
     * <pre>
     *RetType,返回结果
     * </pre>
     *
     * <code>required int32 retType = 1 [default = -400];</code>
     */
    int getRetType();

    /**
     * <code>optional string retMsg = 2;</code>
     */
    boolean hasRetMsg();
    /**
     * <code>optional string retMsg = 2;</code>
     */
    java.lang.String getRetMsg();
    /**
     * <code>optional string retMsg = 2;</code>
     */
    com.google.protobuf.ByteString
        getRetMsgBytes();

    /**
     * <code>optional int32 errCode = 3;</code>
     */
    boolean hasErrCode();
    /**
     * <code>optional int32 errCode = 3;</code>
     */
    int getErrCode();

    /**
     * <code>optional .Qot_UpdateKL.S2C s2c = 4;</code>
     */
    boolean hasS2C();
    /**
     * <code>optional .Qot_UpdateKL.S2C s2c = 4;</code>
     */
    Qot_UpdateKL.QotUpdateKL.S2C getS2C();
    /**
     * <code>optional .Qot_UpdateKL.S2C s2c = 4;</code>
     */
    Qot_UpdateKL.QotUpdateKL.S2COrBuilder getS2COrBuilder();
  }
  /**
   * Protobuf type {@code Qot_UpdateKL.Response}
   */
  public  static final class Response extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Qot_UpdateKL.Response)
      ResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Response.newBuilder() to construct.
    private Response(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Response() {
      retType_ = -400;
      retMsg_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Response(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              bitField0_ |= 0x00000001;
              retType_ = input.readInt32();
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              retMsg_ = bs;
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              errCode_ = input.readInt32();
              break;
            }
            case 34: {
              Qot_UpdateKL.QotUpdateKL.S2C.Builder subBuilder = null;
              if (((bitField0_ & 0x00000008) != 0)) {
                subBuilder = s2C_.toBuilder();
              }
              s2C_ = input.readMessage(Qot_UpdateKL.QotUpdateKL.S2C.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(s2C_);
                s2C_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000008;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Qot_UpdateKL.QotUpdateKL.internal_static_Qot_UpdateKL_Response_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Qot_UpdateKL.QotUpdateKL.internal_static_Qot_UpdateKL_Response_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Qot_UpdateKL.QotUpdateKL.Response.class, Qot_UpdateKL.QotUpdateKL.Response.Builder.class);
    }

    private int bitField0_;
    public static final int RETTYPE_FIELD_NUMBER = 1;
    private int retType_;
    /**
     * <pre>
     *RetType,返回结果
     * </pre>
     *
     * <code>required int32 retType = 1 [default = -400];</code>
     */
    public boolean hasRetType() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     *RetType,返回结果
     * </pre>
     *
     * <code>required int32 retType = 1 [default = -400];</code>
     */
    public int getRetType() {
      return retType_;
    }

    public static final int RETMSG_FIELD_NUMBER = 2;
    private volatile java.lang.Object retMsg_;
    /**
     * <code>optional string retMsg = 2;</code>
     */
    public boolean hasRetMsg() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional string retMsg = 2;</code>
     */
    public java.lang.String getRetMsg() {
      java.lang.Object ref = retMsg_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          retMsg_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string retMsg = 2;</code>
     */
    public com.google.protobuf.ByteString
        getRetMsgBytes() {
      java.lang.Object ref = retMsg_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        retMsg_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ERRCODE_FIELD_NUMBER = 3;
    private int errCode_;
    /**
     * <code>optional int32 errCode = 3;</code>
     */
    public boolean hasErrCode() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional int32 errCode = 3;</code>
     */
    public int getErrCode() {
      return errCode_;
    }

    public static final int S2C_FIELD_NUMBER = 4;
    private Qot_UpdateKL.QotUpdateKL.S2C s2C_;
    /**
     * <code>optional .Qot_UpdateKL.S2C s2c = 4;</code>
     */
    public boolean hasS2C() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>optional .Qot_UpdateKL.S2C s2c = 4;</code>
     */
    public Qot_UpdateKL.QotUpdateKL.S2C getS2C() {
      return s2C_ == null ? Qot_UpdateKL.QotUpdateKL.S2C.getDefaultInstance() : s2C_;
    }
    /**
     * <code>optional .Qot_UpdateKL.S2C s2c = 4;</code>
     */
    public Qot_UpdateKL.QotUpdateKL.S2COrBuilder getS2COrBuilder() {
      return s2C_ == null ? Qot_UpdateKL.QotUpdateKL.S2C.getDefaultInstance() : s2C_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasRetType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (hasS2C()) {
        if (!getS2C().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeInt32(1, retType_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, retMsg_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        output.writeInt32(3, errCode_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        output.writeMessage(4, getS2C());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, retType_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, retMsg_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, errCode_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, getS2C());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Qot_UpdateKL.QotUpdateKL.Response)) {
        return super.equals(obj);
      }
      Qot_UpdateKL.QotUpdateKL.Response other = (Qot_UpdateKL.QotUpdateKL.Response) obj;

      if (hasRetType() != other.hasRetType()) return false;
      if (hasRetType()) {
        if (getRetType()
            != other.getRetType()) return false;
      }
      if (hasRetMsg() != other.hasRetMsg()) return false;
      if (hasRetMsg()) {
        if (!getRetMsg()
            .equals(other.getRetMsg())) return false;
      }
      if (hasErrCode() != other.hasErrCode()) return false;
      if (hasErrCode()) {
        if (getErrCode()
            != other.getErrCode()) return false;
      }
      if (hasS2C() != other.hasS2C()) return false;
      if (hasS2C()) {
        if (!getS2C()
            .equals(other.getS2C())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasRetType()) {
        hash = (37 * hash) + RETTYPE_FIELD_NUMBER;
        hash = (53 * hash) + getRetType();
      }
      if (hasRetMsg()) {
        hash = (37 * hash) + RETMSG_FIELD_NUMBER;
        hash = (53 * hash) + getRetMsg().hashCode();
      }
      if (hasErrCode()) {
        hash = (37 * hash) + ERRCODE_FIELD_NUMBER;
        hash = (53 * hash) + getErrCode();
      }
      if (hasS2C()) {
        hash = (37 * hash) + S2C_FIELD_NUMBER;
        hash = (53 * hash) + getS2C().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Qot_UpdateKL.QotUpdateKL.Response parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Qot_UpdateKL.QotUpdateKL.Response parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Qot_UpdateKL.QotUpdateKL.Response parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Qot_UpdateKL.QotUpdateKL.Response parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Qot_UpdateKL.QotUpdateKL.Response parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Qot_UpdateKL.QotUpdateKL.Response parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Qot_UpdateKL.QotUpdateKL.Response parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Qot_UpdateKL.QotUpdateKL.Response parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Qot_UpdateKL.QotUpdateKL.Response parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Qot_UpdateKL.QotUpdateKL.Response parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Qot_UpdateKL.QotUpdateKL.Response parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Qot_UpdateKL.QotUpdateKL.Response parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Qot_UpdateKL.QotUpdateKL.Response prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Qot_UpdateKL.Response}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Qot_UpdateKL.Response)
        Qot_UpdateKL.QotUpdateKL.ResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Qot_UpdateKL.QotUpdateKL.internal_static_Qot_UpdateKL_Response_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Qot_UpdateKL.QotUpdateKL.internal_static_Qot_UpdateKL_Response_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Qot_UpdateKL.QotUpdateKL.Response.class, Qot_UpdateKL.QotUpdateKL.Response.Builder.class);
      }

      // Construct using Qot_UpdateKL.QotUpdateKL.Response.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getS2CFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        retType_ = -400;
        bitField0_ = (bitField0_ & ~0x00000001);
        retMsg_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        errCode_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        if (s2CBuilder_ == null) {
          s2C_ = null;
        } else {
          s2CBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Qot_UpdateKL.QotUpdateKL.internal_static_Qot_UpdateKL_Response_descriptor;
      }

      @java.lang.Override
      public Qot_UpdateKL.QotUpdateKL.Response getDefaultInstanceForType() {
        return Qot_UpdateKL.QotUpdateKL.Response.getDefaultInstance();
      }

      @java.lang.Override
      public Qot_UpdateKL.QotUpdateKL.Response build() {
        Qot_UpdateKL.QotUpdateKL.Response result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public Qot_UpdateKL.QotUpdateKL.Response buildPartial() {
        Qot_UpdateKL.QotUpdateKL.Response result = new Qot_UpdateKL.QotUpdateKL.Response(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          to_bitField0_ |= 0x00000001;
        }
        result.retType_ = retType_;
        if (((from_bitField0_ & 0x00000002) != 0)) {
          to_bitField0_ |= 0x00000002;
        }
        result.retMsg_ = retMsg_;
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.errCode_ = errCode_;
          to_bitField0_ |= 0x00000004;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          if (s2CBuilder_ == null) {
            result.s2C_ = s2C_;
          } else {
            result.s2C_ = s2CBuilder_.build();
          }
          to_bitField0_ |= 0x00000008;
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Qot_UpdateKL.QotUpdateKL.Response) {
          return mergeFrom((Qot_UpdateKL.QotUpdateKL.Response)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Qot_UpdateKL.QotUpdateKL.Response other) {
        if (other == Qot_UpdateKL.QotUpdateKL.Response.getDefaultInstance()) return this;
        if (other.hasRetType()) {
          setRetType(other.getRetType());
        }
        if (other.hasRetMsg()) {
          bitField0_ |= 0x00000002;
          retMsg_ = other.retMsg_;
          onChanged();
        }
        if (other.hasErrCode()) {
          setErrCode(other.getErrCode());
        }
        if (other.hasS2C()) {
          mergeS2C(other.getS2C());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasRetType()) {
          return false;
        }
        if (hasS2C()) {
          if (!getS2C().isInitialized()) {
            return false;
          }
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Qot_UpdateKL.QotUpdateKL.Response parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Qot_UpdateKL.QotUpdateKL.Response) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int retType_ = -400;
      /**
       * <pre>
       *RetType,返回结果
       * </pre>
       *
       * <code>required int32 retType = 1 [default = -400];</code>
       */
      public boolean hasRetType() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <pre>
       *RetType,返回结果
       * </pre>
       *
       * <code>required int32 retType = 1 [default = -400];</code>
       */
      public int getRetType() {
        return retType_;
      }
      /**
       * <pre>
       *RetType,返回结果
       * </pre>
       *
       * <code>required int32 retType = 1 [default = -400];</code>
       */
      public Builder setRetType(int value) {
        bitField0_ |= 0x00000001;
        retType_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *RetType,返回结果
       * </pre>
       *
       * <code>required int32 retType = 1 [default = -400];</code>
       */
      public Builder clearRetType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        retType_ = -400;
        onChanged();
        return this;
      }

      private java.lang.Object retMsg_ = "";
      /**
       * <code>optional string retMsg = 2;</code>
       */
      public boolean hasRetMsg() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>optional string retMsg = 2;</code>
       */
      public java.lang.String getRetMsg() {
        java.lang.Object ref = retMsg_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            retMsg_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string retMsg = 2;</code>
       */
      public com.google.protobuf.ByteString
          getRetMsgBytes() {
        java.lang.Object ref = retMsg_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          retMsg_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string retMsg = 2;</code>
       */
      public Builder setRetMsg(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        retMsg_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string retMsg = 2;</code>
       */
      public Builder clearRetMsg() {
        bitField0_ = (bitField0_ & ~0x00000002);
        retMsg_ = getDefaultInstance().getRetMsg();
        onChanged();
        return this;
      }
      /**
       * <code>optional string retMsg = 2;</code>
       */
      public Builder setRetMsgBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        retMsg_ = value;
        onChanged();
        return this;
      }

      private int errCode_ ;
      /**
       * <code>optional int32 errCode = 3;</code>
       */
      public boolean hasErrCode() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>optional int32 errCode = 3;</code>
       */
      public int getErrCode() {
        return errCode_;
      }
      /**
       * <code>optional int32 errCode = 3;</code>
       */
      public Builder setErrCode(int value) {
        bitField0_ |= 0x00000004;
        errCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 errCode = 3;</code>
       */
      public Builder clearErrCode() {
        bitField0_ = (bitField0_ & ~0x00000004);
        errCode_ = 0;
        onChanged();
        return this;
      }

      private Qot_UpdateKL.QotUpdateKL.S2C s2C_;
      private com.google.protobuf.SingleFieldBuilderV3<
          Qot_UpdateKL.QotUpdateKL.S2C, Qot_UpdateKL.QotUpdateKL.S2C.Builder, Qot_UpdateKL.QotUpdateKL.S2COrBuilder> s2CBuilder_;
      /**
       * <code>optional .Qot_UpdateKL.S2C s2c = 4;</code>
       */
      public boolean hasS2C() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <code>optional .Qot_UpdateKL.S2C s2c = 4;</code>
       */
      public Qot_UpdateKL.QotUpdateKL.S2C getS2C() {
        if (s2CBuilder_ == null) {
          return s2C_ == null ? Qot_UpdateKL.QotUpdateKL.S2C.getDefaultInstance() : s2C_;
        } else {
          return s2CBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .Qot_UpdateKL.S2C s2c = 4;</code>
       */
      public Builder setS2C(Qot_UpdateKL.QotUpdateKL.S2C value) {
        if (s2CBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          s2C_ = value;
          onChanged();
        } else {
          s2CBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <code>optional .Qot_UpdateKL.S2C s2c = 4;</code>
       */
      public Builder setS2C(
          Qot_UpdateKL.QotUpdateKL.S2C.Builder builderForValue) {
        if (s2CBuilder_ == null) {
          s2C_ = builderForValue.build();
          onChanged();
        } else {
          s2CBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <code>optional .Qot_UpdateKL.S2C s2c = 4;</code>
       */
      public Builder mergeS2C(Qot_UpdateKL.QotUpdateKL.S2C value) {
        if (s2CBuilder_ == null) {
          if (((bitField0_ & 0x00000008) != 0) &&
              s2C_ != null &&
              s2C_ != Qot_UpdateKL.QotUpdateKL.S2C.getDefaultInstance()) {
            s2C_ =
              Qot_UpdateKL.QotUpdateKL.S2C.newBuilder(s2C_).mergeFrom(value).buildPartial();
          } else {
            s2C_ = value;
          }
          onChanged();
        } else {
          s2CBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <code>optional .Qot_UpdateKL.S2C s2c = 4;</code>
       */
      public Builder clearS2C() {
        if (s2CBuilder_ == null) {
          s2C_ = null;
          onChanged();
        } else {
          s2CBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }
      /**
       * <code>optional .Qot_UpdateKL.S2C s2c = 4;</code>
       */
      public Qot_UpdateKL.QotUpdateKL.S2C.Builder getS2CBuilder() {
        bitField0_ |= 0x00000008;
        onChanged();
        return getS2CFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .Qot_UpdateKL.S2C s2c = 4;</code>
       */
      public Qot_UpdateKL.QotUpdateKL.S2COrBuilder getS2COrBuilder() {
        if (s2CBuilder_ != null) {
          return s2CBuilder_.getMessageOrBuilder();
        } else {
          return s2C_ == null ?
              Qot_UpdateKL.QotUpdateKL.S2C.getDefaultInstance() : s2C_;
        }
      }
      /**
       * <code>optional .Qot_UpdateKL.S2C s2c = 4;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          Qot_UpdateKL.QotUpdateKL.S2C, Qot_UpdateKL.QotUpdateKL.S2C.Builder, Qot_UpdateKL.QotUpdateKL.S2COrBuilder> 
          getS2CFieldBuilder() {
        if (s2CBuilder_ == null) {
          s2CBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              Qot_UpdateKL.QotUpdateKL.S2C, Qot_UpdateKL.QotUpdateKL.S2C.Builder, Qot_UpdateKL.QotUpdateKL.S2COrBuilder>(
                  getS2C(),
                  getParentForChildren(),
                  isClean());
          s2C_ = null;
        }
        return s2CBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Qot_UpdateKL.Response)
    }

    // @@protoc_insertion_point(class_scope:Qot_UpdateKL.Response)
    private static final Qot_UpdateKL.QotUpdateKL.Response DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Qot_UpdateKL.QotUpdateKL.Response();
    }

    public static Qot_UpdateKL.QotUpdateKL.Response getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Response>
        PARSER = new com.google.protobuf.AbstractParser<Response>() {
      @java.lang.Override
      public Response parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Response(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Response> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Response> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public Qot_UpdateKL.QotUpdateKL.Response getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Qot_UpdateKL_S2C_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Qot_UpdateKL_S2C_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Qot_UpdateKL_Response_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Qot_UpdateKL_Response_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022Qot_UpdateKL.proto\022\014Qot_UpdateKL\032\014Comm" +
      "on.proto\032\020Qot_Common.proto\"s\n\003S2C\022\021\n\treh" +
      "abType\030\001 \002(\005\022\016\n\006klType\030\002 \002(\005\022&\n\010security" +
      "\030\003 \002(\0132\024.Qot_Common.Security\022!\n\006klList\030\004" +
      " \003(\0132\021.Qot_Common.KLine\"b\n\010Response\022\025\n\007r" +
      "etType\030\001 \002(\005:\004-400\022\016\n\006retMsg\030\002 \001(\t\022\017\n\007er" +
      "rCode\030\003 \001(\005\022\036\n\003s2c\030\004 \001(\0132\021.Qot_UpdateKL." +
      "S2C"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          Common.Common.getDescriptor(),
          Qot_Common.QotCommon.getDescriptor(),
        }, assigner);
    internal_static_Qot_UpdateKL_S2C_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Qot_UpdateKL_S2C_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Qot_UpdateKL_S2C_descriptor,
        new java.lang.String[] { "RehabType", "KlType", "Security", "KlList", });
    internal_static_Qot_UpdateKL_Response_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Qot_UpdateKL_Response_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Qot_UpdateKL_Response_descriptor,
        new java.lang.String[] { "RetType", "RetMsg", "ErrCode", "S2C", });
    Common.Common.getDescriptor();
    Qot_Common.QotCommon.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
